// Key Items catalog for Vanalytics's Key Items tab.
//
// Source: Windower's Resources/resources_data/key_items.lua (canonical FFXI
// key item list). Filtered:
//   - Category "Temporary Key Items" dropped wholesale (1628 transient items)
//   - XIchecklist's maps/keyitems_exclusions.lua excluded + hidden sets
//     (debug items, retired event items, magical map duplicates)
//
// Categories preserved: Permanent Key Items, Magical Maps, Mounts,
// Active Effects, Voidwatch, Abyssea, Mog Garden, Claim Slips, Geas Fete.
// Geas Fete is current endgame content not in XIchecklist's tab list — we
// include it since players want to track those.

export interface KeyItemCatalogEntry {
    id: number
    name: string
    category: KeyItemCategory
}

export type KeyItemCategory =
    | 'Permanent Key Items'
    | 'Magical Maps'
    | 'Mounts'
    | 'Active Effects'
    | 'Voidwatch'
    | 'Abyssea'
    | 'Mog Garden'
    | 'Claim Slips'
    | 'Geas Fete'

export const KEY_ITEM_CATEGORIES: KeyItemCategory[] = [
    'Permanent Key Items',
    'Mounts',
    'Magical Maps',
    'Mog Garden',
    'Voidwatch',
    'Abyssea',
    'Geas Fete',
    'Active Effects',
    'Claim Slips',
]

export const KEY_ITEMS: KeyItemCatalogEntry[] = [
    { id: 8, name: "airship pass", category: "Permanent Key Items" },
    { id: 9, name: "airship pass for Kazham", category: "Permanent Key Items" },
    { id: 20, name: "Yagudo torch", category: "Permanent Key Items" },
    { id: 21, name: "crest of Davoi", category: "Permanent Key Items" },
    { id: 35, name: "Adventurer's Certificate", category: "Permanent Key Items" },
    { id: 36, name: "Starway Stairway bauble", category: "Permanent Key Items" },
    { id: 45, name: "silver bell", category: "Permanent Key Items" },
    { id: 46, name: "coruscant rosary", category: "Permanent Key Items" },
    { id: 47, name: "black matinee necklace", category: "Permanent Key Items" },
    { id: 56, name: "archducal audience permit", category: "Permanent Key Items" },
    { id: 95, name: "fake moustache", category: "Permanent Key Items" },
    { id: 116, name: "Angelica's autograph", category: "Permanent Key Items" },
    { id: 118, name: "Tenshodo Member's Card", category: "Permanent Key Items" },
    { id: 136, name: "crimson orb", category: "Permanent Key Items" },
    { id: 138, name: "chocobo license", category: "Permanent Key Items" },
    { id: 142, name: "squire certificate", category: "Permanent Key Items" },
    { id: 155, name: "scroll of treasure", category: "Permanent Key Items" },
    { id: 162, name: "carrier pigeon letter", category: "Permanent Key Items" },
    { id: 169, name: "testimonial", category: "Permanent Key Items" },
    { id: 195, name: "portal charm", category: "Permanent Key Items" },
    { id: 247, name: "prismatic fragment", category: "Permanent Key Items" },
    { id: 267, name: "Rhinostery certificate", category: "Permanent Key Items" },
    { id: 272, name: "paintbrush of souls", category: "Permanent Key Items" },
    { id: 291, name: "Tonberry key", category: "Permanent Key Items" },
    { id: 349, name: "White Card", category: "Permanent Key Items" },
    { id: 351, name: "Black Card", category: "Permanent Key Items" },
    { id: 352, name: "Holla gate crystal", category: "Permanent Key Items" },
    { id: 353, name: "Dem gate crystal", category: "Permanent Key Items" },
    { id: 354, name: "Mea gate crystal", category: "Permanent Key Items" },
    { id: 355, name: "Vahzl gate crystal", category: "Permanent Key Items" },
    { id: 356, name: "Yhoator gate crystal", category: "Permanent Key Items" },
    { id: 357, name: "Altepa gate crystal", category: "Permanent Key Items" },
    { id: 361, name: "whisper of the Wyrmking", category: "Permanent Key Items" },
    { id: 365, name: "tattered Maze Monger pouch", category: "Permanent Key Items" },
    { id: 383, name: "map of Abdh. Isle-Purgonorgo", category: "Magical Maps" },
    { id: 385, name: "map of the San d'Oria area", category: "Magical Maps" },
    { id: 386, name: "map of the Bastok area", category: "Magical Maps" },
    { id: 387, name: "map of the Windurst area", category: "Magical Maps" },
    { id: 388, name: "map of the Jeuno area", category: "Magical Maps" },
    { id: 389, name: "map of Qufim Island", category: "Magical Maps" },
    { id: 390, name: "map of the Northlands area", category: "Magical Maps" },
    { id: 391, name: "map of King Ranperre's Tomb", category: "Magical Maps" },
    { id: 392, name: "map of the Dangruf Wadi", category: "Magical Maps" },
    { id: 393, name: "map of the Horutoto Ruins", category: "Magical Maps" },
    { id: 394, name: "map of Bostaunieux Oubliette", category: "Magical Maps" },
    { id: 395, name: "map of the Zeruhn Mines", category: "Magical Maps" },
    { id: 396, name: "map of the Toraimarai Canal", category: "Magical Maps" },
    { id: 397, name: "map of Ordelle's Caves", category: "Magical Maps" },
    { id: 398, name: "map of the Gusgen Mines", category: "Magical Maps" },
    { id: 399, name: "map of the Maze of Shakhrami", category: "Magical Maps" },
    { id: 400, name: "map of the Eldieme Necropolis", category: "Magical Maps" },
    { id: 401, name: "map of the Crawlers' Nest", category: "Magical Maps" },
    { id: 402, name: "map of the Garlaige Citadel", category: "Magical Maps" },
    { id: 403, name: "map of the Ranguemont Pass", category: "Magical Maps" },
    { id: 404, name: "map of Ghelsba", category: "Magical Maps" },
    { id: 405, name: "map of Davoi", category: "Magical Maps" },
    { id: 406, name: "map of the Palborough Mines", category: "Magical Maps" },
    { id: 407, name: "map of Beadeaux", category: "Magical Maps" },
    { id: 408, name: "map of Giddeus", category: "Magical Maps" },
    { id: 409, name: "map of Castle Oztroja", category: "Magical Maps" },
    { id: 410, name: "map of Delkfutt's Tower", category: "Magical Maps" },
    { id: 411, name: "map of Fei'Yin", category: "Magical Maps" },
    { id: 412, name: "map of Castle Zvahl", category: "Magical Maps" },
    { id: 413, name: "map of the Elshimo regions", category: "Magical Maps" },
    { id: 414, name: "map of the Kuzotz region", category: "Magical Maps" },
    { id: 415, name: "map of the Li'Telor region", category: "Magical Maps" },
    { id: 416, name: "map of the Ru'Aun Gardens", category: "Magical Maps" },
    { id: 417, name: "map of Norg", category: "Magical Maps" },
    { id: 418, name: "map of Temple of Uggalepih", category: "Magical Maps" },
    { id: 419, name: "map of the Den of Rancor", category: "Magical Maps" },
    { id: 420, name: "map of the Korroloka Tunnel", category: "Magical Maps" },
    { id: 421, name: "map of the Kuftal Tunnel", category: "Magical Maps" },
    { id: 422, name: "map of the Boyahda Tree", category: "Magical Maps" },
    { id: 423, name: "map of Ve'Lugannon Palace", category: "Magical Maps" },
    { id: 424, name: "map of Ifrit's Cauldron", category: "Magical Maps" },
    { id: 425, name: "map of the Quicksand Caves", category: "Magical Maps" },
    { id: 426, name: "map of Sea Serpent Grotto", category: "Magical Maps" },
    { id: 427, name: "map of the Vollbow region", category: "Magical Maps" },
    { id: 428, name: "map of Labyrinth of Onzozo", category: "Magical Maps" },
    { id: 429, name: "map of Carpenters' Landing", category: "Magical Maps" },
    { id: 430, name: "map of Bibiki Bay", category: "Magical Maps" },
    { id: 431, name: "map of the Uleguerand Range", category: "Magical Maps" },
    { id: 432, name: "map of the Attohwa Chasm", category: "Magical Maps" },
    { id: 433, name: "map of Pso'Xja", category: "Magical Maps" },
    { id: 434, name: "map of Oldton Movalpolos", category: "Magical Maps" },
    { id: 435, name: "map of Newton Movalpolos", category: "Magical Maps" },
    { id: 436, name: "map of Promyvion - Holla", category: "Magical Maps" },
    { id: 437, name: "map of Promyvion - Dem", category: "Magical Maps" },
    { id: 438, name: "map of Promyvion - Mea", category: "Magical Maps" },
    { id: 439, name: "map of Promyvion - Vahzl", category: "Magical Maps" },
    { id: 440, name: "map of Tavnazia", category: "Magical Maps" },
    { id: 441, name: "map of the Aqueducts", category: "Magical Maps" },
    { id: 442, name: "map of the Sacrarium", category: "Magical Maps" },
    { id: 443, name: "map of Cape Riverne", category: "Magical Maps" },
    { id: 444, name: "map of Al'Taieu", category: "Magical Maps" },
    { id: 445, name: "map of Hu'Xzoi", category: "Magical Maps" },
    { id: 446, name: "map of Ru'Hmet", category: "Magical Maps" },
    { id: 447, name: "map of Dio. Abdhaljs-Ghelsba", category: "Magical Maps" },
    { id: 452, name: "cerulean crystal", category: "Permanent Key Items" },
    { id: 455, name: "Shard of Apathy", category: "Permanent Key Items" },
    { id: 456, name: "Shard of Arrogance", category: "Permanent Key Items" },
    { id: 457, name: "Shard of Cowardice", category: "Permanent Key Items" },
    { id: 458, name: "Shard of Envy", category: "Permanent Key Items" },
    { id: 459, name: "Shard of Rage", category: "Permanent Key Items" },
    { id: 485, name: "moongate pass", category: "Permanent Key Items" },
    { id: 486, name: "Hydra Corps Command Scepter", category: "Permanent Key Items" },
    { id: 487, name: "Hydra Corps Eyeglass", category: "Permanent Key Items" },
    { id: 488, name: "Hydra Corps Lantern", category: "Permanent Key Items" },
    { id: 489, name: "Hydra Corps Tactical Map", category: "Permanent Key Items" },
    { id: 490, name: "Hydra Corps Insignia", category: "Permanent Key Items" },
    { id: 491, name: "Hydra Corps Battle Standard", category: "Permanent Key Items" },
    { id: 492, name: "vial of shrouded sand", category: "Permanent Key Items" },
    { id: 576, name: "Ballista License", category: "Permanent Key Items" },
    { id: 582, name: "reliquiarium key", category: "Permanent Key Items" },
    { id: 595, name: "blue bracelet", category: "Permanent Key Items" },
    { id: 596, name: "green bracelet", category: "Permanent Key Items" },
    { id: 604, name: "Pso'Xja pass", category: "Permanent Key Items" },
    { id: 606, name: "limit breaker", category: "Permanent Key Items" },
    { id: 654, name: "fighter's armor claim slip", category: "Claim Slips" },
    { id: 655, name: "temple attire claim slip", category: "Claim Slips" },
    { id: 656, name: "healer's attire claim slip", category: "Claim Slips" },
    { id: 657, name: "wizard's attire claim slip", category: "Claim Slips" },
    { id: 658, name: "warlock's armor claim slip", category: "Claim Slips" },
    { id: 659, name: "rogue's attire claim slip", category: "Claim Slips" },
    { id: 660, name: "gallant armor claim slip", category: "Claim Slips" },
    { id: 661, name: "chaos armor claim slip", category: "Claim Slips" },
    { id: 662, name: "beast armor claim slip", category: "Claim Slips" },
    { id: 663, name: "choral attire claim slip", category: "Claim Slips" },
    { id: 664, name: "hunter's attire claim slip", category: "Claim Slips" },
    { id: 665, name: "myochin armor claim slip", category: "Claim Slips" },
    { id: 666, name: "ninja's garb claim slip", category: "Claim Slips" },
    { id: 667, name: "drachen armor claim slip", category: "Claim Slips" },
    { id: 668, name: "evoker's attire claim slip", category: "Claim Slips" },
    { id: 710, name: "Brand of Dawn", category: "Permanent Key Items" },
    { id: 711, name: "Brand of Twilight", category: "Permanent Key Items" },
    { id: 716, name: "Tear of Altana", category: "Permanent Key Items" },
    { id: 718, name: "Shaded Cruse", category: "Permanent Key Items" },
    { id: 728, name: "jar of reversion dust", category: "Permanent Key Items" },
    { id: 739, name: "Dynamis - Valkurm sliver", category: "Permanent Key Items" },
    { id: 740, name: "Dynamis - Buburimu sliver", category: "Permanent Key Items" },
    { id: 741, name: "Dynamis - Qufim sliver", category: "Permanent Key Items" },
    { id: 742, name: "Dynamis - Tavnazia sliver", category: "Permanent Key Items" },
    { id: 767, name: "Dkhaaya's research journal", category: "Permanent Key Items" },
    { id: 771, name: "Mark of Zahak", category: "Permanent Key Items" },
    { id: 774, name: "cast metal plate", category: "Permanent Key Items" },
    { id: 781, name: "boarding permit", category: "Permanent Key Items" },
    { id: 812, name: "astral compass", category: "Permanent Key Items" },
    { id: 829, name: "Brand of the Springserpent", category: "Permanent Key Items" },
    { id: 830, name: "Brand of the Galeserpent", category: "Permanent Key Items" },
    { id: 831, name: "Brand of the Flameserpent", category: "Permanent Key Items" },
    { id: 832, name: "Brand of the Skyserpent", category: "Permanent Key Items" },
    { id: 833, name: "Brand of the Stoneserpent", category: "Permanent Key Items" },
    { id: 851, name: "prairie chocograph", category: "Permanent Key Items" },
    { id: 852, name: "bush chocograph", category: "Permanent Key Items" },
    { id: 856, name: "coastal chocograph", category: "Permanent Key Items" },
    { id: 857, name: "dune chocograph", category: "Permanent Key Items" },
    { id: 858, name: "jungle chocograph", category: "Permanent Key Items" },
    { id: 859, name: "desert chocograph", category: "Permanent Key Items" },
    { id: 861, name: "warrior's armor claim slip", category: "Claim Slips" },
    { id: 862, name: "melee attire claim slip", category: "Claim Slips" },
    { id: 863, name: "cleric's attire claim slip", category: "Claim Slips" },
    { id: 864, name: "sorcerer's attire claim slip", category: "Claim Slips" },
    { id: 865, name: "duelist's armor claim slip", category: "Claim Slips" },
    { id: 866, name: "assassin's attire claim slip", category: "Claim Slips" },
    { id: 867, name: "valor armor claim slip", category: "Claim Slips" },
    { id: 868, name: "abyss armor claim slip", category: "Claim Slips" },
    { id: 869, name: "monster armor claim slip", category: "Claim Slips" },
    { id: 870, name: "bard's attire claim slip", category: "Claim Slips" },
    { id: 871, name: "scout's attire claim slip", category: "Claim Slips" },
    { id: 872, name: "saotome armor claim slip", category: "Claim Slips" },
    { id: 873, name: "koga garb claim slip", category: "Claim Slips" },
    { id: 874, name: "wyrm armor claim slip", category: "Claim Slips" },
    { id: 875, name: "summoner's attire claim slip", category: "Claim Slips" },
    { id: 879, name: "runic disc", category: "Permanent Key Items" },
    { id: 880, name: "runic key", category: "Permanent Key Items" },
    { id: 881, name: "Gysahl Medal", category: "Permanent Key Items" },
    { id: 891, name: "Mark of the Einherjar", category: "Permanent Key Items" },
    { id: 909, name: "Captain Wildcat badge", category: "Permanent Key Items" },
    { id: 910, name: "pure white feather", category: "Permanent Key Items" },
    { id: 944, name: "sliced pole", category: "Permanent Key Items" },
    { id: 946, name: "grimoire", category: "Permanent Key Items" },
    { id: 962, name: "\"The Essence of Dance\"", category: "Permanent Key Items" },
    { id: 963, name: "Jugner gate crystal", category: "Permanent Key Items" },
    { id: 964, name: "Pashhow gate crystal", category: "Permanent Key Items" },
    { id: 965, name: "Meriphataud gate crystal", category: "Permanent Key Items" },
    { id: 1024, name: "Sakura racing badge", category: "Permanent Key Items" },
    { id: 1054, name: "mirage attire claim slip", category: "Claim Slips" },
    { id: 1055, name: "commodore attire claim slip", category: "Claim Slips" },
    { id: 1056, name: "pantin attire claim slip", category: "Claim Slips" },
    { id: 1057, name: "etoile attire claim slip", category: "Claim Slips" },
    { id: 1058, name: "argute attire claim slip", category: "Claim Slips" },
    { id: 1059, name: "argent attire claim slip", category: "Claim Slips" },
    { id: 1111, name: "Delkfutt key", category: "Permanent Key Items" },
    { id: 1163, name: "Ponono's charm", category: "Permanent Key Items" },
    { id: 1234, name: "synergy crucible", category: "Permanent Key Items" },
    { id: 1247, name: "Megomak's shopping list", category: "Permanent Key Items" },
    { id: 1250, name: "message from Yoyoroon", category: "Permanent Key Items" },
    { id: 1261, name: "Magian trial log", category: "Permanent Key Items" },
    { id: 1279, name: "Atma of the Lion", category: "Abyssea" },
    { id: 1280, name: "Atma of the Stout Arm", category: "Abyssea" },
    { id: 1281, name: "Atma of the Twin Claw", category: "Abyssea" },
    { id: 1282, name: "Atma of Allure", category: "Abyssea" },
    { id: 1283, name: "Atma of Eternity", category: "Abyssea" },
    { id: 1284, name: "Atma of the Heavens", category: "Abyssea" },
    { id: 1285, name: "Atma of the Baying Moon", category: "Abyssea" },
    { id: 1286, name: "Atma of the Ebon Hoof", category: "Abyssea" },
    { id: 1287, name: "Atma of Tremors", category: "Abyssea" },
    { id: 1288, name: "Atma of the Savage Tiger", category: "Abyssea" },
    { id: 1289, name: "Atma of the Voracious Violet", category: "Abyssea" },
    { id: 1290, name: "Atma of Cloak and Dagger", category: "Abyssea" },
    { id: 1291, name: "Atma of the Stormbird", category: "Abyssea" },
    { id: 1292, name: "Atma of the Noxious Fang", category: "Abyssea" },
    { id: 1293, name: "Atma of Vicissitude", category: "Abyssea" },
    { id: 1294, name: "Atma of the Beyond", category: "Abyssea" },
    { id: 1295, name: "Atma of Stormbreath", category: "Abyssea" },
    { id: 1296, name: "Atma of Gales", category: "Abyssea" },
    { id: 1297, name: "Atma of Thrashing Tendrils", category: "Abyssea" },
    { id: 1298, name: "Atma of the Drifter", category: "Abyssea" },
    { id: 1299, name: "Atma of the Stronghold", category: "Abyssea" },
    { id: 1300, name: "Atma of the Harvester", category: "Abyssea" },
    { id: 1301, name: "Atma of Dunes", category: "Abyssea" },
    { id: 1302, name: "Atma of the Cosmos", category: "Abyssea" },
    { id: 1303, name: "Atma of the Siren Shadow", category: "Abyssea" },
    { id: 1304, name: "Atma of the Impaler", category: "Abyssea" },
    { id: 1305, name: "Atma of the Adamantine", category: "Abyssea" },
    { id: 1306, name: "Atma of Calamity", category: "Abyssea" },
    { id: 1307, name: "Atma of the Claw", category: "Abyssea" },
    { id: 1308, name: "Atma of Baleful Bones", category: "Abyssea" },
    { id: 1309, name: "Atma of the Clawed Butterfly", category: "Abyssea" },
    { id: 1310, name: "Atma of the Desert Worm", category: "Abyssea" },
    { id: 1311, name: "Atma of the Undying", category: "Abyssea" },
    { id: 1312, name: "Atma of the Impregnable Tower", category: "Abyssea" },
    { id: 1313, name: "Atma of the Smoldering Sky", category: "Abyssea" },
    { id: 1314, name: "Atma of the Demonic Skewer", category: "Abyssea" },
    { id: 1315, name: "Atma of the Golden Claw", category: "Abyssea" },
    { id: 1316, name: "Atma of the Glutinous Ooze", category: "Abyssea" },
    { id: 1317, name: "Atma of the Lightning Beast", category: "Abyssea" },
    { id: 1318, name: "Atma of the Noxious Bloom", category: "Abyssea" },
    { id: 1319, name: "Atma of the Gnarled Horn", category: "Abyssea" },
    { id: 1320, name: "Atma of the Strangling Wind", category: "Abyssea" },
    { id: 1321, name: "Atma of the Deep Devourer", category: "Abyssea" },
    { id: 1322, name: "Atma of the Mounted Champion", category: "Abyssea" },
    { id: 1323, name: "Atma of the Razed Ruins", category: "Abyssea" },
    { id: 1324, name: "Atma of the Bludgeoning Brute", category: "Abyssea" },
    { id: 1325, name: "Atma of the Rapid Reptilian", category: "Abyssea" },
    { id: 1326, name: "Atma of the Winged Enigma", category: "Abyssea" },
    { id: 1327, name: "Atma of the Cradle", category: "Abyssea" },
    { id: 1328, name: "Atma of the Untouched", category: "Abyssea" },
    { id: 1329, name: "Atma of the Sanguine Scythe", category: "Abyssea" },
    { id: 1330, name: "Atma of the Tusked Terror", category: "Abyssea" },
    { id: 1331, name: "Atma of the Minikin Monstrosity", category: "Abyssea" },
    { id: 1332, name: "Atma of the Would-Be King", category: "Abyssea" },
    { id: 1333, name: "Atma of the Blinding Horn", category: "Abyssea" },
    { id: 1334, name: "Atma of the Demonic Lash", category: "Abyssea" },
    { id: 1335, name: "Atma of Apparitions", category: "Abyssea" },
    { id: 1336, name: "Atma of the Shimmering Shell", category: "Abyssea" },
    { id: 1337, name: "Atma of the Murky Miasma", category: "Abyssea" },
    { id: 1338, name: "Atma of the Avaricious Ape", category: "Abyssea" },
    { id: 1339, name: "Atma of the Merciless Matriarch", category: "Abyssea" },
    { id: 1340, name: "Atma of the Brother Wolf", category: "Abyssea" },
    { id: 1341, name: "Atma of the Earth Wyrm", category: "Abyssea" },
    { id: 1342, name: "Atma of the Ascending One", category: "Abyssea" },
    { id: 1343, name: "Atma of the Scorpion Queen", category: "Abyssea" },
    { id: 1344, name: "Atma of a Thousand Needles", category: "Abyssea" },
    { id: 1345, name: "Atma of the Burning Effigy", category: "Abyssea" },
    { id: 1346, name: "Atma of the Smiting Blow", category: "Abyssea" },
    { id: 1347, name: "Atma of the Lone Wolf", category: "Abyssea" },
    { id: 1348, name: "Atma of the Crimson Scale", category: "Abyssea" },
    { id: 1349, name: "Atma of the Scarlet Wing", category: "Abyssea" },
    { id: 1350, name: "Atma of the Raised Tail", category: "Abyssea" },
    { id: 1351, name: "Atma of the Sand Emperor", category: "Abyssea" },
    { id: 1352, name: "Atma of the Omnipotent", category: "Abyssea" },
    { id: 1353, name: "Atma of the War Lion", category: "Abyssea" },
    { id: 1354, name: "Atma of the Frozen Fetters", category: "Abyssea" },
    { id: 1355, name: "Atma of the Plaguebringer", category: "Abyssea" },
    { id: 1356, name: "Atma of the Shrieking One", category: "Abyssea" },
    { id: 1357, name: "Atma of the Holy Mountain", category: "Abyssea" },
    { id: 1358, name: "Atma of the Lake Lurker", category: "Abyssea" },
    { id: 1359, name: "Atma of the Crushing Cudgel", category: "Abyssea" },
    { id: 1360, name: "Atma of Purgatory", category: "Abyssea" },
    { id: 1361, name: "Atma of Blighted Breath", category: "Abyssea" },
    { id: 1362, name: "Atma of the Persistent Predator", category: "Abyssea" },
    { id: 1363, name: "Atma of the Stone God", category: "Abyssea" },
    { id: 1364, name: "Atma of the Sun Eater", category: "Abyssea" },
    { id: 1365, name: "Atma of the Despot", category: "Abyssea" },
    { id: 1366, name: "Atma of the Solitary One", category: "Abyssea" },
    { id: 1367, name: "Atma of the Winged Gloom", category: "Abyssea" },
    { id: 1368, name: "Atma of the Sea Daughter", category: "Abyssea" },
    { id: 1369, name: "Atma of the Hateful Stream", category: "Abyssea" },
    { id: 1370, name: "Atma of the Foe Flayer", category: "Abyssea" },
    { id: 1371, name: "Atma of the Endless Nightmare", category: "Abyssea" },
    { id: 1372, name: "Atma of the Sundering Slash", category: "Abyssea" },
    { id: 1373, name: "Atma of Entwined Serpents", category: "Abyssea" },
    { id: 1374, name: "Atma of the Horned Beast", category: "Abyssea" },
    { id: 1375, name: "Atma of Aquatic Ardor", category: "Abyssea" },
    { id: 1376, name: "Atma of the Fallen One", category: "Abyssea" },
    { id: 1377, name: "Atma of Fires and Flares", category: "Abyssea" },
    { id: 1378, name: "Atma of the Apocalypse", category: "Abyssea" },
    { id: 1379, name: "ivory abyssite of sojourn", category: "Abyssea" },
    { id: 1380, name: "scarlet abyssite of sojourn", category: "Abyssea" },
    { id: 1381, name: "jade abyssite of sojourn", category: "Abyssea" },
    { id: 1382, name: "sapphire abyssite of sojourn", category: "Abyssea" },
    { id: 1383, name: "indigo abyssite of sojourn", category: "Abyssea" },
    { id: 1384, name: "emerald abyssite of sojourn", category: "Abyssea" },
    { id: 1385, name: "azure abyssite of celerity", category: "Abyssea" },
    { id: 1386, name: "crimson abyssite of celerity", category: "Abyssea" },
    { id: 1387, name: "ivory abyssite of celerity", category: "Abyssea" },
    { id: 1388, name: "viridian abyssite of avarice", category: "Abyssea" },
    { id: 1389, name: "ivory abyssite of avarice", category: "Abyssea" },
    { id: 1390, name: "vermillion abyssite of avarice", category: "Abyssea" },
    { id: 1391, name: "ivory abyssite of confluence", category: "Abyssea" },
    { id: 1392, name: "crimson abyssite of confluence", category: "Abyssea" },
    { id: 1393, name: "indigo abyssite of confluence", category: "Abyssea" },
    { id: 1394, name: "ivory abyssite of expertise", category: "Abyssea" },
    { id: 1395, name: "jade abyssite of expertise", category: "Abyssea" },
    { id: 1396, name: "emerald abyssite of expertise", category: "Abyssea" },
    { id: 1397, name: "ivory abyssite of fortune", category: "Abyssea" },
    { id: 1398, name: "sapphire abyssite of fortune", category: "Abyssea" },
    { id: 1399, name: "emerald abyssite of fortune", category: "Abyssea" },
    { id: 1400, name: "scarlet abyssite of kismet", category: "Abyssea" },
    { id: 1401, name: "ivory abyssite of kismet", category: "Abyssea" },
    { id: 1402, name: "vermillion abyssite of kismet", category: "Abyssea" },
    { id: 1403, name: "azure abyssite of prosperity", category: "Abyssea" },
    { id: 1404, name: "jade abyssite of prosperity", category: "Abyssea" },
    { id: 1405, name: "ivory abyssite of prosperity", category: "Abyssea" },
    { id: 1406, name: "viridian abyssite of destiny", category: "Abyssea" },
    { id: 1407, name: "crimson abyssite of destiny", category: "Abyssea" },
    { id: 1408, name: "ivory abyssite of destiny", category: "Abyssea" },
    { id: 1409, name: "ivory abyssite of acumen", category: "Abyssea" },
    { id: 1410, name: "crimson abyssite of acumen", category: "Abyssea" },
    { id: 1411, name: "emerald abyssite of acumen", category: "Abyssea" },
    { id: 1412, name: "scarlet abyssite of lenity", category: "Abyssea" },
    { id: 1413, name: "azure abyssite of lenity", category: "Abyssea" },
    { id: 1414, name: "viridian abyssite of lenity", category: "Abyssea" },
    { id: 1415, name: "jade abyssite of lenity", category: "Abyssea" },
    { id: 1416, name: "sapphire abyssite of lenity", category: "Abyssea" },
    { id: 1417, name: "crimson abyssite of lenity", category: "Abyssea" },
    { id: 1418, name: "vermillion abyssite of lenity", category: "Abyssea" },
    { id: 1419, name: "indigo abyssite of lenity", category: "Abyssea" },
    { id: 1420, name: "emerald abyssite of lenity", category: "Abyssea" },
    { id: 1421, name: "scarlet abyssite of perspicacity", category: "Abyssea" },
    { id: 1422, name: "ivory abyssite of perspicacity", category: "Abyssea" },
    { id: 1423, name: "verm. abyssite of perspicacity", category: "Abyssea" },
    { id: 1424, name: "azure abyssite of the reaper", category: "Abyssea" },
    { id: 1425, name: "ivory abyssite of the reaper", category: "Abyssea" },
    { id: 1426, name: "indigo abyssite of the reaper", category: "Abyssea" },
    { id: 1427, name: "viridian abyssite of guerdon", category: "Abyssea" },
    { id: 1428, name: "ivory abyssite of guerdon", category: "Abyssea" },
    { id: 1429, name: "vermillion abyssite of guerdon", category: "Abyssea" },
    { id: 1430, name: "scarlet abyssite of furtherance", category: "Abyssea" },
    { id: 1431, name: "sapphire abyssite of furtherance", category: "Abyssea" },
    { id: 1432, name: "ivory abyssite of furtherance", category: "Abyssea" },
    { id: 1433, name: "azure abyssite of merit", category: "Abyssea" },
    { id: 1434, name: "viridian abyssite of merit", category: "Abyssea" },
    { id: 1435, name: "jade abyssite of merit", category: "Abyssea" },
    { id: 1436, name: "sapphire abyssite of merit", category: "Abyssea" },
    { id: 1437, name: "ivory abyssite of merit", category: "Abyssea" },
    { id: 1438, name: "indigo abyssite of merit", category: "Abyssea" },
    { id: 1439, name: "lunar abyssite", category: "Abyssea" },
    { id: 1440, name: "lunar abyssite", category: "Abyssea" },
    { id: 1441, name: "lunar abyssite", category: "Abyssea" },
    { id: 1442, name: "abyssite of discernment", category: "Abyssea" },
    { id: 1443, name: "abyssite of the cosmos", category: "Abyssea" },
    { id: 1550, name: "prismatic hourglass", category: "Permanent Key Items" },
    { id: 1655, name: "Atma of the Heir", category: "Abyssea" },
    { id: 1656, name: "Atma of the Hero", category: "Abyssea" },
    { id: 1657, name: "Atma of the Full Moon", category: "Abyssea" },
    { id: 1658, name: "Atma of Illusions", category: "Abyssea" },
    { id: 1659, name: "Atma of the Banisher", category: "Abyssea" },
    { id: 1660, name: "Atma of the Sellsword", category: "Abyssea" },
    { id: 1661, name: "Atma of a Future Fabulous", category: "Abyssea" },
    { id: 1662, name: "Atma of Camaraderie", category: "Abyssea" },
    { id: 1663, name: "Atma of the Truthseeker", category: "Abyssea" },
    { id: 1664, name: "Atma of the Azure Sky", category: "Abyssea" },
    { id: 1665, name: "Atma of Echoes", category: "Abyssea" },
    { id: 1666, name: "Atma of Dread", category: "Abyssea" },
    { id: 1667, name: "Atma of Ambition", category: "Abyssea" },
    { id: 1668, name: "Atma of the Beast King", category: "Abyssea" },
    { id: 1669, name: "Atma of the Kirin", category: "Abyssea" },
    { id: 1670, name: "Atma of Hell's Guardian", category: "Abyssea" },
    { id: 1671, name: "Atma of Luminous Wings", category: "Abyssea" },
    { id: 1672, name: "Atma of the Dragon Rider", category: "Abyssea" },
    { id: 1673, name: "Atma of the Impenetrable", category: "Abyssea" },
    { id: 1674, name: "Atma of Alpha and Omega", category: "Abyssea" },
    { id: 1675, name: "Atma of the Ultimate", category: "Abyssea" },
    { id: 1676, name: "Atma of the Hybrid Beast", category: "Abyssea" },
    { id: 1677, name: "Atma of the Dark Depths", category: "Abyssea" },
    { id: 1678, name: "Atma of the Zenith", category: "Abyssea" },
    { id: 1679, name: "Atma of Perfect Attendance", category: "Abyssea" },
    { id: 1680, name: "Atma of the Rescuer", category: "Abyssea" },
    { id: 1681, name: "Atma of Nightmares", category: "Abyssea" },
    { id: 1682, name: "Atma of the Einherjar", category: "Abyssea" },
    { id: 1683, name: "Atma of the Illuminator", category: "Abyssea" },
    { id: 1684, name: "Atma of the Bushin", category: "Abyssea" },
    { id: 1685, name: "Atma of the Ace Angler", category: "Abyssea" },
    { id: 1686, name: "Atma of the Master Crafter", category: "Abyssea" },
    { id: 1687, name: "Atma of Ingenuity", category: "Abyssea" },
    { id: 1688, name: "Atma of the Griffon's Claw", category: "Abyssea" },
    { id: 1689, name: "Atma of the Fetching Footpad", category: "Abyssea" },
    { id: 1690, name: "Atma of Undying Loyalty", category: "Abyssea" },
    { id: 1691, name: "Atma of the Royal Lineage", category: "Abyssea" },
    { id: 1692, name: "Atma of the Shattering Star", category: "Abyssea" },
    { id: 1693, name: "Atma of the Cobra Commander", category: "Abyssea" },
    { id: 1694, name: "Atma of Roaring Laughter", category: "Abyssea" },
    { id: 1695, name: "Atma of the Dark Blade", category: "Abyssea" },
    { id: 1696, name: "Atma of the Ducal Guard", category: "Abyssea" },
    { id: 1697, name: "Atma of Harmony", category: "Abyssea" },
    { id: 1698, name: "Atma of Revelations", category: "Abyssea" },
    { id: 1699, name: "Atma of the Savior", category: "Abyssea" },
    { id: 1738, name: "job gesture: warrior", category: "Permanent Key Items" },
    { id: 1739, name: "job gesture: monk", category: "Permanent Key Items" },
    { id: 1740, name: "job gesture: white mage", category: "Permanent Key Items" },
    { id: 1741, name: "job gesture: black mage", category: "Permanent Key Items" },
    { id: 1742, name: "job gesture: red mage", category: "Permanent Key Items" },
    { id: 1743, name: "job gesture: thief", category: "Permanent Key Items" },
    { id: 1744, name: "job gesture: paladin", category: "Permanent Key Items" },
    { id: 1745, name: "job gesture: dark knight", category: "Permanent Key Items" },
    { id: 1746, name: "job gesture: beastmaster", category: "Permanent Key Items" },
    { id: 1747, name: "job gesture: bard", category: "Permanent Key Items" },
    { id: 1748, name: "job gesture: ranger", category: "Permanent Key Items" },
    { id: 1749, name: "job gesture: samurai", category: "Permanent Key Items" },
    { id: 1750, name: "job gesture: ninja", category: "Permanent Key Items" },
    { id: 1751, name: "job gesture: dragoon", category: "Permanent Key Items" },
    { id: 1752, name: "job gesture: summoner", category: "Permanent Key Items" },
    { id: 1753, name: "job gesture: blue mage", category: "Permanent Key Items" },
    { id: 1754, name: "job gesture: corsair", category: "Permanent Key Items" },
    { id: 1755, name: "job gesture: puppetmaster", category: "Permanent Key Items" },
    { id: 1756, name: "job gesture: dancer", category: "Permanent Key Items" },
    { id: 1757, name: "job gesture: scholar", category: "Permanent Key Items" },
    { id: 1767, name: "Magian learner's log", category: "Permanent Key Items" },
    { id: 1774, name: "periapt of emergence", category: "Voidwatch" },
    { id: 1775, name: "periapt of emergence", category: "Voidwatch" },
    { id: 1776, name: "periapt of emergence", category: "Voidwatch" },
    { id: 1777, name: "periapt of guidance", category: "Voidwatch" },
    { id: 1778, name: "periapt of percipience", category: "Voidwatch" },
    { id: 1779, name: "vivid periapt of concord", category: "Voidwatch" },
    { id: 1780, name: "dusky periapt of concord", category: "Voidwatch" },
    { id: 1781, name: "vivid periapt of catalysis", category: "Voidwatch" },
    { id: 1782, name: "dusky periapt of catalysis", category: "Voidwatch" },
    { id: 1783, name: "vivid periapt of exploration", category: "Voidwatch" },
    { id: 1784, name: "dusky periapt of exploration", category: "Voidwatch" },
    { id: 1785, name: "vivid periapt of frontiers", category: "Voidwatch" },
    { id: 1786, name: "dusky periapt of frontiers", category: "Voidwatch" },
    { id: 1787, name: "neutral periapt of frontiers", category: "Voidwatch" },
    { id: 1788, name: "vivid periapt of concentration", category: "Voidwatch" },
    { id: 1789, name: "dusky periapt of concentration", category: "Voidwatch" },
    { id: 1790, name: "vivid periapt of glory", category: "Voidwatch" },
    { id: 1791, name: "dusky periapt of glory", category: "Voidwatch" },
    { id: 1792, name: "vivid periapt of focus", category: "Voidwatch" },
    { id: 1793, name: "dusky periapt of focus", category: "Voidwatch" },
    { id: 1794, name: "vivid periapt of intensity", category: "Voidwatch" },
    { id: 1795, name: "dusky periapt of intensity", category: "Voidwatch" },
    { id: 1796, name: "vivid periapt of readiness", category: "Voidwatch" },
    { id: 1797, name: "dusky periapt of readiness", category: "Voidwatch" },
    { id: 1798, name: "vivid periapt of adaptability", category: "Voidwatch" },
    { id: 1799, name: "dusky periapt of adaptability", category: "Voidwatch" },
    { id: 1800, name: "vivid periapt of vigilance", category: "Voidwatch" },
    { id: 1801, name: "dusky periapt of vigilance", category: "Voidwatch" },
    { id: 1802, name: "vivid periapt of prudence", category: "Voidwatch" },
    { id: 1803, name: "dusky periapt of prudence", category: "Voidwatch" },
    { id: 1804, name: "periapt of recompense", category: "Voidwatch" },
    { id: 1806, name: "Atmacite of Devotion", category: "Voidwatch" },
    { id: 1807, name: "Atmacite of Persistence", category: "Voidwatch" },
    { id: 1808, name: "Atmacite of Eminence", category: "Voidwatch" },
    { id: 1809, name: "Atmacite of Onslaught", category: "Voidwatch" },
    { id: 1810, name: "Atmacite of Incursion", category: "Voidwatch" },
    { id: 1811, name: "Atmacite of Enticement", category: "Voidwatch" },
    { id: 1812, name: "Atmacite of Destruction", category: "Voidwatch" },
    { id: 1813, name: "Atmacite of Temperance", category: "Voidwatch" },
    { id: 1814, name: "Atmacite of Discipline", category: "Voidwatch" },
    { id: 1815, name: "Atmacite of Coercion", category: "Voidwatch" },
    { id: 1816, name: "Atmacite of Finesse", category: "Voidwatch" },
    { id: 1817, name: "Atmacite of Latitude", category: "Voidwatch" },
    { id: 1818, name: "Atmacite of Mysticism", category: "Voidwatch" },
    { id: 1819, name: "Atmacite of Rapidity", category: "Voidwatch" },
    { id: 1820, name: "Atmacite of Preparedness", category: "Voidwatch" },
    { id: 1821, name: "Atmacite of Deluges", category: "Voidwatch" },
    { id: 1822, name: "Atmacite of Unity", category: "Voidwatch" },
    { id: 1823, name: "Atmacite of Exhortation", category: "Voidwatch" },
    { id: 1824, name: "Atmacite of Skyblaze", category: "Voidwatch" },
    { id: 1825, name: "Atmacite of the Slayer", category: "Voidwatch" },
    { id: 1826, name: "Atmacite of the Adamant", category: "Voidwatch" },
    { id: 1827, name: "Atmacite of the Valiant", category: "Voidwatch" },
    { id: 1828, name: "Atmacite of the Shrewd", category: "Voidwatch" },
    { id: 1829, name: "Atmacite of the Vanguard", category: "Voidwatch" },
    { id: 1830, name: "Atmacite of Assailment", category: "Voidwatch" },
    { id: 1831, name: "Atmacite of Cataphract", category: "Voidwatch" },
    { id: 1832, name: "Atmacite of the Parapet", category: "Voidwatch" },
    { id: 1833, name: "Atmacite of Imperium", category: "Voidwatch" },
    { id: 1834, name: "Atmacite of the Solipsist", category: "Voidwatch" },
    { id: 1835, name: "Atmacite of Provenance", category: "Voidwatch" },
    { id: 1836, name: "Atmacite of Dark Designs", category: "Voidwatch" },
    { id: 1837, name: "Atmacite of the Forager", category: "Voidwatch" },
    { id: 1838, name: "Atmacite of Glaciers", category: "Voidwatch" },
    { id: 1839, name: "Atmacite of Affinity", category: "Voidwatch" },
    { id: 1840, name: "Atmacite of the Depths", category: "Voidwatch" },
    { id: 1841, name: "Atmacite of the Assassin", category: "Voidwatch" },
    { id: 1842, name: "Atmacite of Aplomb", category: "Voidwatch" },
    { id: 1843, name: "Atmacite of the Tropics", category: "Voidwatch" },
    { id: 1844, name: "Atmacite of Curses", category: "Voidwatch" },
    { id: 1845, name: "Atmacite of Preservation", category: "Voidwatch" },
    { id: 1846, name: "pouch of weighted stones", category: "Permanent Key Items" },
    { id: 1854, name: "periapt of sapience", category: "Voidwatch" },
    { id: 1855, name: "periapt of clarity", category: "Voidwatch" },
    { id: 1856, name: "map of Al Zahbi", category: "Magical Maps" },
    { id: 1857, name: "map of Nashmau", category: "Magical Maps" },
    { id: 1858, name: "map of Wajaom Woodlands", category: "Magical Maps" },
    { id: 1859, name: "map of Caedarva Mire", category: "Magical Maps" },
    { id: 1860, name: "map of Mount Zhayolm", category: "Magical Maps" },
    { id: 1861, name: "map of Aydeewa Subterrane", category: "Magical Maps" },
    { id: 1862, name: "map of Mamook", category: "Magical Maps" },
    { id: 1863, name: "map of Halvung", category: "Magical Maps" },
    { id: 1864, name: "map of Arrapago Reef", category: "Magical Maps" },
    { id: 1865, name: "map of Alzadaal Ruins", category: "Magical Maps" },
    { id: 1872, name: "map of the Chocobo Circuit", category: "Magical Maps" },
    { id: 1874, name: "map of Bhaflau Thickets", category: "Magical Maps" },
    { id: 1879, name: "map of Vunkerl Inlet", category: "Magical Maps" },
    { id: 1881, name: "map of Grauberg", category: "Magical Maps" },
    { id: 1883, name: "map of Fort Karugo-Narugo", category: "Magical Maps" },
    { id: 1885, name: "map of Abyssea - La Theine", category: "Magical Maps" },
    { id: 1886, name: "map of Abyssea - Konschtat", category: "Magical Maps" },
    { id: 1887, name: "map of Abyssea - Tahrongi", category: "Magical Maps" },
    { id: 1888, name: "map of Abyssea - Attohwa", category: "Magical Maps" },
    { id: 1889, name: "map of Abyssea - Misareaux", category: "Magical Maps" },
    { id: 1890, name: "map of Abyssea - Vunkerl", category: "Magical Maps" },
    { id: 1891, name: "map of Abyssea - Altepa", category: "Magical Maps" },
    { id: 1892, name: "map of Abyssea - Uleguerand", category: "Magical Maps" },
    { id: 1893, name: "map of Abyssea - Grauberg", category: "Magical Maps" },
    { id: 1894, name: "map of Dynamis - San d'Oria", category: "Magical Maps" },
    { id: 1895, name: "map of Dynamis - Bastok", category: "Magical Maps" },
    { id: 1896, name: "map of Dynamis - Windurst", category: "Magical Maps" },
    { id: 1897, name: "map of Dynamis - Jeuno", category: "Magical Maps" },
    { id: 1898, name: "map of Dynamis - Beaucedine", category: "Magical Maps" },
    { id: 1899, name: "map of Dynamis - Xarcabard", category: "Magical Maps" },
    { id: 1900, name: "map of Dynamis - Valkurm", category: "Magical Maps" },
    { id: 1901, name: "map of Dynamis - Buburimu", category: "Magical Maps" },
    { id: 1902, name: "map of Dynamis - Qufim", category: "Magical Maps" },
    { id: 1903, name: "map of Dynamis - Tavnazia", category: "Magical Maps" },
    { id: 1904, name: "map of Adoulin", category: "Magical Maps" },
    { id: 1905, name: "map of Rala Waterways", category: "Magical Maps" },
    { id: 1906, name: "map of Yahse Hunting Grounds", category: "Magical Maps" },
    { id: 1907, name: "map of Ceizak Battlegrounds", category: "Magical Maps" },
    { id: 1908, name: "map of Foret de Hennetiel", category: "Magical Maps" },
    { id: 1909, name: "map of Yorcia Weald", category: "Magical Maps" },
    { id: 1910, name: "map of Morimar Basalt Fields", category: "Magical Maps" },
    { id: 1911, name: "map of Marjami Ravine", category: "Magical Maps" },
    { id: 1912, name: "map of Kamihr Drifts", category: "Magical Maps" },
    { id: 1913, name: "map of Sih Gates", category: "Magical Maps" },
    { id: 1914, name: "map of Moh Gates", category: "Magical Maps" },
    { id: 1915, name: "map of Cirdas Caverns", category: "Magical Maps" },
    { id: 1916, name: "map of Dho Gates", category: "Magical Maps" },
    { id: 1917, name: "map of Woh Gates", category: "Magical Maps" },
    { id: 1918, name: "map of Ra'Kaznar", category: "Magical Maps" },
    { id: 1920, name: "iron chainmail claim slip", category: "Claim Slips" },
    { id: 1921, name: "shade harness claim slip", category: "Claim Slips" },
    { id: 1922, name: "brass scale mail claim slip", category: "Claim Slips" },
    { id: 1923, name: "wool robe claim slip", category: "Claim Slips" },
    { id: 1924, name: "eisenplatte armor claim slip", category: "Claim Slips" },
    { id: 1925, name: "soil gi claim slip", category: "Claim Slips" },
    { id: 1926, name: "seer's tunic claim slip", category: "Claim Slips" },
    { id: 1927, name: "studded armor claim slip", category: "Claim Slips" },
    { id: 1928, name: "centurion's scale mail claim slip", category: "Claim Slips" },
    { id: 1929, name: "mrc.cpt. doublet claim slip", category: "Claim Slips" },
    { id: 1930, name: "garish tunic claim slip", category: "Claim Slips" },
    { id: 1931, name: "noct doublet claim slip", category: "Claim Slips" },
    { id: 1932, name: "custom armor (♂) claim slip", category: "Claim Slips" },
    { id: 1933, name: "custom armor (♀) claim slip", category: "Claim Slips" },
    { id: 1934, name: "magna armor (♂) claim slip", category: "Claim Slips" },
    { id: 1935, name: "magna armor (♀) claim slip", category: "Claim Slips" },
    { id: 1936, name: "wonder armor claim slip", category: "Claim Slips" },
    { id: 1937, name: "savage armor claim slip", category: "Claim Slips" },
    { id: 1938, name: "elder armor claim slip", category: "Claim Slips" },
    { id: 1939, name: "linen cloak claim slip", category: "Claim Slips" },
    { id: 1940, name: "padded armor claim slip", category: "Claim Slips" },
    { id: 1941, name: "silver chainmail claim slip", category: "Claim Slips" },
    { id: 1942, name: "gambison claim slip", category: "Claim Slips" },
    { id: 1943, name: "iron scale armor claim slip", category: "Claim Slips" },
    { id: 1944, name: "cuir armor claim slip", category: "Claim Slips" },
    { id: 1945, name: "velvet robe claim slip", category: "Claim Slips" },
    { id: 1946, name: "opaline dress claim slip", category: "Claim Slips" },
    { id: 1947, name: "ryl.sqr. chainmail claim slip", category: "Claim Slips" },
    { id: 1948, name: "plate armor claim slip", category: "Claim Slips" },
    { id: 1949, name: "combat caster's cloak claim slip", category: "Claim Slips" },
    { id: 1950, name: "alumine haubert claim slip", category: "Claim Slips" },
    { id: 1951, name: "carapace harness claim slip", category: "Claim Slips" },
    { id: 1952, name: "banded mail claim slip", category: "Claim Slips" },
    { id: 1953, name: "hara-ate claim slip", category: "Claim Slips" },
    { id: 1954, name: "raptor armor claim slip", category: "Claim Slips" },
    { id: 1955, name: "steel scale armor claim slip", category: "Claim Slips" },
    { id: 1956, name: "wool gambison claim slip", category: "Claim Slips" },
    { id: 1957, name: "shinobi gi claim slip", category: "Claim Slips" },
    { id: 1958, name: "irn.msk. cuirass claim slip", category: "Claim Slips" },
    { id: 1959, name: "tct.mgc. cloak claim slip", category: "Claim Slips" },
    { id: 1960, name: "white cloak claim slip", category: "Claim Slips" },
    { id: 1961, name: "austere robe claim slip", category: "Claim Slips" },
    { id: 1962, name: "mythril plate armor claim slip", category: "Claim Slips" },
    { id: 1963, name: "crow jupon claim slip", category: "Claim Slips" },
    { id: 1964, name: "magus attire claim slip", category: "Claim Slips" },
    { id: 1965, name: "corsair's attire claim slip", category: "Claim Slips" },
    { id: 1966, name: "puppetry attire claim slip", category: "Claim Slips" },
    { id: 1967, name: "dancer's attire claim slip", category: "Claim Slips" },
    { id: 1968, name: "dancer's attire claim slip", category: "Claim Slips" },
    { id: 1969, name: "scholar's attire claim slip", category: "Claim Slips" },
    { id: 1970, name: "Amir armor claim slip", category: "Claim Slips" },
    { id: 1971, name: "Pahluwan armor claim slip", category: "Claim Slips" },
    { id: 1972, name: "Yigit armor claim slip", category: "Claim Slips" },
    { id: 1976, name: "Frog Fishing", category: "Permanent Key Items" },
    { id: 1977, name: "Serpent Rumors", category: "Permanent Key Items" },
    { id: 1978, name: "Mooching", category: "Permanent Key Items" },
    { id: 1979, name: "Anglers' Almanac", category: "Permanent Key Items" },
    { id: 1984, name: "Wood Purification", category: "Permanent Key Items" },
    { id: 1985, name: "Wood Ensorcellment", category: "Permanent Key Items" },
    { id: 1986, name: "Lumberjack", category: "Permanent Key Items" },
    { id: 1987, name: "Boltmaker", category: "Permanent Key Items" },
    { id: 1988, name: "Way of the Carpenter", category: "Permanent Key Items" },
    { id: 1992, name: "Metal Purification", category: "Permanent Key Items" },
    { id: 1993, name: "Metal Ensorcellment", category: "Permanent Key Items" },
    { id: 1994, name: "Chainwork", category: "Permanent Key Items" },
    { id: 1995, name: "Sheeting", category: "Permanent Key Items" },
    { id: 1996, name: "Way of the Blacksmith", category: "Permanent Key Items" },
    { id: 2000, name: "Gold Purification", category: "Permanent Key Items" },
    { id: 2001, name: "Gold Ensorcellment", category: "Permanent Key Items" },
    { id: 2002, name: "Clockmaking", category: "Permanent Key Items" },
    { id: 2003, name: "Way of the Goldsmith", category: "Permanent Key Items" },
    { id: 2008, name: "Cloth Purification", category: "Permanent Key Items" },
    { id: 2009, name: "Cloth Ensorcellment", category: "Permanent Key Items" },
    { id: 2010, name: "Spinning", category: "Permanent Key Items" },
    { id: 2011, name: "Fletching", category: "Permanent Key Items" },
    { id: 2012, name: "Way of the Weaver", category: "Permanent Key Items" },
    { id: 2016, name: "Leather Purification", category: "Permanent Key Items" },
    { id: 2017, name: "Leather Ensorcellment", category: "Permanent Key Items" },
    { id: 2018, name: "Tanning", category: "Permanent Key Items" },
    { id: 2019, name: "Way of the Tanner", category: "Permanent Key Items" },
    { id: 2024, name: "Bone Purification", category: "Permanent Key Items" },
    { id: 2025, name: "Bone Ensorcellment", category: "Permanent Key Items" },
    { id: 2026, name: "Filing", category: "Permanent Key Items" },
    { id: 2027, name: "Way of the Boneworker", category: "Permanent Key Items" },
    { id: 2032, name: "Anima Synthesis", category: "Permanent Key Items" },
    { id: 2033, name: "Alchemic Purification", category: "Permanent Key Items" },
    { id: 2034, name: "Alchemic Ensorcellment", category: "Permanent Key Items" },
    { id: 2035, name: "Trituration", category: "Permanent Key Items" },
    { id: 2036, name: "Concoction", category: "Permanent Key Items" },
    { id: 2037, name: "Iatrochemistry", category: "Permanent Key Items" },
    { id: 2038, name: "miasmal counteragent recipe", category: "Permanent Key Items" },
    { id: 2039, name: "Way of the Alchemist", category: "Permanent Key Items" },
    { id: 2040, name: "Raw Fish Handling", category: "Permanent Key Items" },
    { id: 2041, name: "Noodle Kneading", category: "Permanent Key Items" },
    { id: 2042, name: "Patissier", category: "Permanent Key Items" },
    { id: 2043, name: "Stewpot Mastery", category: "Permanent Key Items" },
    { id: 2044, name: "Way of the Culinarian", category: "Permanent Key Items" },
    { id: 2049, name: "Voidwatcher's emblem: Jeuno", category: "Voidwatch" },
    { id: 2050, name: "Voidwatcher's emblem: Qufim", category: "Voidwatch" },
    { id: 2051, name: "loadstone", category: "Permanent Key Items" },
    { id: 2054, name: "tricolor Voidwatcher's emblem", category: "Voidwatch" },
    { id: 2055, name: "starlight Voidwatcher's emblem", category: "Voidwatch" },
    { id: 2059, name: "heart of the bushin", category: "Permanent Key Items" },
    { id: 2061, name: "hyacinth stratum abyssite II", category: "Voidwatch" },
    { id: 2063, name: "amber stratum abyssite II", category: "Voidwatch" },
    { id: 2064, name: "clairvoy ant", category: "Voidwatch" },
    { id: 2152, name: "sheet of San d'Orian tunes", category: "Permanent Key Items" },
    { id: 2153, name: "sheet of Bastokan tunes", category: "Permanent Key Items" },
    { id: 2154, name: "sheet of Windurstian tunes", category: "Permanent Key Items" },
    { id: 2155, name: "geomagnetron", category: "Permanent Key Items" },
    { id: 2156, name: "Adoulinian charter permit", category: "Permanent Key Items" },
    { id: 2157, name: "Pioneer's Badge", category: "Permanent Key Items" },
    { id: 2159, name: "aged Matriarch Naakual crest", category: "Permanent Key Items" },
    { id: 2160, name: "aged Riptide Naakual crest", category: "Permanent Key Items" },
    { id: 2161, name: "aged Firebrand Naakual crest", category: "Permanent Key Items" },
    { id: 2162, name: "aged Ligneous Naakual crest", category: "Permanent Key Items" },
    { id: 2163, name: "aged Booming Naakual crest", category: "Permanent Key Items" },
    { id: 2164, name: "aged Flashfrost Naakual crest", category: "Permanent Key Items" },
    { id: 2165, name: "aged Undying Naakual crest", category: "Permanent Key Items" },
    { id: 2166, name: "prototype attuner", category: "Permanent Key Items" },
    { id: 2167, name: "watercraft", category: "Permanent Key Items" },
    { id: 2171, name: "restrainment resilience", category: "Permanent Key Items" },
    { id: 2196, name: "geomagnetic compass", category: "Permanent Key Items" },
    { id: 2204, name: "\"Logging\"", category: "Permanent Key Items" },
    { id: 2205, name: "\"Watercrafting\"", category: "Permanent Key Items" },
    { id: 2206, name: "\"Demolishing\"", category: "Permanent Key Items" },
    { id: 2207, name: "toxin resilience", category: "Permanent Key Items" },
    { id: 2208, name: "paresis resilience", category: "Permanent Key Items" },
    { id: 2209, name: "calor resilience", category: "Permanent Key Items" },
    { id: 2234, name: "reive unity", category: "Permanent Key Items" },
    { id: 2236, name: "\"Critical Chop\"", category: "Permanent Key Items" },
    { id: 2237, name: "\"Cherished Axe\"", category: "Permanent Key Items" },
    { id: 2238, name: "\"Critical Smash\"", category: "Permanent Key Items" },
    { id: 2239, name: "\"Cherished Pick\"", category: "Permanent Key Items" },
    { id: 2240, name: "\"Critical Slice\"", category: "Permanent Key Items" },
    { id: 2241, name: "\"Cherished Sickle\"", category: "Permanent Key Items" },
    { id: 2242, name: "\"Redoubled Chop\"", category: "Permanent Key Items" },
    { id: 2243, name: "\"Conservative Chop\"", category: "Permanent Key Items" },
    { id: 2244, name: "\"Redoubled Smash\"", category: "Permanent Key Items" },
    { id: 2245, name: "\"Conservative Smash\"", category: "Permanent Key Items" },
    { id: 2246, name: "\"Redoubled Slice\"", category: "Permanent Key Items" },
    { id: 2247, name: "\"Conservative Slice\"", category: "Permanent Key Items" },
    { id: 2248, name: "San d'Oria warp rune", category: "Permanent Key Items" },
    { id: 2249, name: "Bastok warp rune", category: "Permanent Key Items" },
    { id: 2250, name: "Windurst warp rune", category: "Permanent Key Items" },
    { id: 2251, name: "Selbina warp rune", category: "Permanent Key Items" },
    { id: 2252, name: "Mhaura warp rune", category: "Permanent Key Items" },
    { id: 2253, name: "Kazham warp rune", category: "Permanent Key Items" },
    { id: 2254, name: "Rabao warp rune", category: "Permanent Key Items" },
    { id: 2255, name: "Norg warp rune", category: "Permanent Key Items" },
    { id: 2256, name: "Tavnazia warp rune", category: "Permanent Key Items" },
    { id: 2257, name: "Whitegate warp rune", category: "Permanent Key Items" },
    { id: 2258, name: "Nashmau warp rune", category: "Permanent Key Items" },
    { id: 2280, name: "habitual behavior barometer", category: "Permanent Key Items" },
    { id: 2290, name: "luopan", category: "Permanent Key Items" },
    { id: 2307, name: "map of Escha - Zi'Tah", category: "Magical Maps" },
    { id: 2308, name: "map of Escha - Ru'Aun", category: "Magical Maps" },
    { id: 2309, name: "map of Reisenjima", category: "Magical Maps" },
    { id: 2341, name: "sheet of E. Adoulinian tunes", category: "Permanent Key Items" },
    { id: 2342, name: "sheet of W. Adoulinian tunes", category: "Permanent Key Items" },
    { id: 2344, name: "impure celadon yggzi", category: "Permanent Key Items" },
    { id: 2345, name: "semi-pure celadon yggzi", category: "Permanent Key Items" },
    { id: 2346, name: "impure zaffre yggzi", category: "Permanent Key Items" },
    { id: 2347, name: "semi-pure zaffre yggzi", category: "Permanent Key Items" },
    { id: 2348, name: "impure alizarin yggzi", category: "Permanent Key Items" },
    { id: 2349, name: "semi-pure alizarin yggzi", category: "Permanent Key Items" },
    { id: 2350, name: "ring of supernal disjunction", category: "Permanent Key Items" },
    { id: 2353, name: "\"Enlightened Endeavor\"", category: "Permanent Key Items" },
    { id: 2388, name: "\"Climbing\"", category: "Permanent Key Items" },
    { id: 2393, name: "ivory wing talisman", category: "Permanent Key Items" },
    { id: 2394, name: "bronze mattock cordon", category: "Permanent Key Items" },
    { id: 2395, name: "bronze shovel cordon", category: "Permanent Key Items" },
    { id: 2398, name: "GPS crystal", category: "Mog Garden" },
    { id: 2399, name: "pair of Velkk gloves", category: "Permanent Key Items" },
    { id: 2410, name: "Rosulatia's pome", category: "Permanent Key Items" },
    { id: 2411, name: "Celennia Memorial Library card", category: "Permanent Key Items" },
    { id: 2412, name: "\"Sow★Your★Seed!\"", category: "Mog Garden" },
    { id: 2413, name: "\"My First Furrow\"", category: "Mog Garden" },
    { id: 2414, name: "\"Fields And Fertilizing\"", category: "Mog Garden" },
    { id: 2415, name: "\"Designer Farming\"", category: "Mog Garden" },
    { id: 2416, name: "\"Homesteader's Compendium\"", category: "Mog Garden" },
    { id: 2417, name: "\"MHMU Treatise on Agronomy\"", category: "Mog Garden" },
    { id: 2419, name: "\"Give My Regards to Reodoan\"", category: "Mog Garden" },
    { id: 2420, name: "\"Adoulin's Topiary Treasures\"", category: "Mog Garden" },
    { id: 2421, name: "\"Grandiloquent Groves\"", category: "Mog Garden" },
    { id: 2422, name: "\"Arboreal Abracadabra\"", category: "Mog Garden" },
    { id: 2423, name: "\"Verdant and Verdon'ts\"", category: "Mog Garden" },
    { id: 2424, name: "\"MHMU Treatise on Forestry\"", category: "Mog Garden" },
    { id: 2426, name: "\"Mythril Marathon Quarterly\"", category: "Mog Garden" },
    { id: 2427, name: "\"Take A Lode Off\"", category: "Mog Garden" },
    { id: 2428, name: "\"Varicose Mineral Veins\"", category: "Mog Garden" },
    { id: 2429, name: "\"Tales from the Tunnel\"", category: "Mog Garden" },
    { id: 2430, name: "\"The Gusgen Mines Tragedy\"", category: "Mog Garden" },
    { id: 2431, name: "\"MHMU Treatise on Minerals\"", category: "Mog Garden" },
    { id: 2433, name: "\"A Farewell to Freshwater\"", category: "Mog Garden" },
    { id: 2434, name: "\"Water, Water Everywhere!\"", category: "Mog Garden" },
    { id: 2435, name: "\"Dredging's No Drudgery\"", category: "Mog Garden" },
    { id: 2436, name: "\"All the Ways to Skin a Carp\"", category: "Mog Garden" },
    { id: 2437, name: "\"Anatomy of an Angler\"", category: "Mog Garden" },
    { id: 2438, name: "\"MHMU Treatise on Fish I\"", category: "Mog Garden" },
    { id: 2440, name: "\"The Old Men of the Sea\"", category: "Mog Garden" },
    { id: 2441, name: "\"Susuroon's Biiig Catch\"", category: "Mog Garden" },
    { id: 2442, name: "\"Black Fish of the Family\"", category: "Mog Garden" },
    { id: 2443, name: "\"20,000 Yalms Under the Sea\"", category: "Mog Garden" },
    { id: 2444, name: "\"Encyclopedia Icthyonnica\"", category: "Mog Garden" },
    { id: 2445, name: "\"MHMU Treatise on Fish II\"", category: "Mog Garden" },
    { id: 2452, name: "gil repository", category: "Mog Garden" },
    { id: 2453, name: "crab caller", category: "Mog Garden" },
    { id: 2461, name: "\"Fragmenting\"", category: "Permanent Key Items" },
    { id: 2462, name: "pair of fuzzy earmuffs", category: "Permanent Key Items" },
    { id: 2466, name: "memorandoll", category: "Permanent Key Items" },
    { id: 2467, name: "algor resilience", category: "Permanent Key Items" },
    { id: 2497, name: "Windurst Trust permit", category: "Permanent Key Items" },
    { id: 2499, name: "Bastok Trust permit", category: "Permanent Key Items" },
    { id: 2501, name: "San d'Oria Trust permit", category: "Permanent Key Items" },
    { id: 2503, name: "\"Pulverizing\"", category: "Permanent Key Items" },
    { id: 2504, name: "Lerene's paten", category: "Permanent Key Items" },
    { id: 2506, name: "Temple Knight key", category: "Permanent Key Items" },
    { id: 2508, name: "silvery plate", category: "Permanent Key Items" },
    { id: 2510, name: "bundle of half-inscribed scrolls", category: "Permanent Key Items" },
    { id: 2535, name: "impure phlox yggzi", category: "Permanent Key Items" },
    { id: 2536, name: "semi-pure phlox yggzi", category: "Permanent Key Items" },
    { id: 2537, name: "impure russet yggzi", category: "Permanent Key Items" },
    { id: 2538, name: "semi-pure russet yggzi", category: "Permanent Key Items" },
    { id: 2539, name: "impure aster yggzi", category: "Permanent Key Items" },
    { id: 2540, name: "semi-pure aster yggzi", category: "Permanent Key Items" },
    { id: 2544, name: "job breaker", category: "Permanent Key Items" },
    { id: 2547, name: "Peppe-Aleppe's superlative tonic", category: "Permanent Key Items" },
    { id: 2548, name: "Sajj'aka's protective ward", category: "Permanent Key Items" },
    { id: 2553, name: "ivory wing talisman", category: "Permanent Key Items" },
    { id: 2554, name: "silver mattock cordon", category: "Permanent Key Items" },
    { id: 2555, name: "silver shovel cordon", category: "Permanent Key Items" },
    { id: 2564, name: "sheet of Zilart tunes", category: "Permanent Key Items" },
    { id: 2573, name: "\"Quiescence\"", category: "Permanent Key Items" },
    { id: 2578, name: "magicked astrolabe", category: "Permanent Key Items" },
    { id: 2579, name: "bracelet of verve", category: "Permanent Key Items" },
    { id: 2599, name: "sepulcher ensign", category: "Permanent Key Items" },
    { id: 2624, name: "Ashrakk's blood sigil", category: "Permanent Key Items" },
    { id: 2625, name: "Dhokmak's blood sigil", category: "Permanent Key Items" },
    { id: 2627, name: "Teodor's blood sigil", category: "Permanent Key Items" },
    { id: 2629, name: "Arciela's spare bonnet", category: "Permanent Key Items" },
    { id: 2630, name: "Arciela's skirt", category: "Permanent Key Items" },
    { id: 2631, name: "concordoll", category: "Permanent Key Items" },
    { id: 2633, name: "\"Sakura and the Magic Spoon\"", category: "Mog Garden" },
    { id: 2642, name: "lamb memento", category: "Mog Garden" },
    { id: 2643, name: "sheep memento", category: "Mog Garden" },
    { id: 2644, name: "karakul memento", category: "Mog Garden" },
    { id: 2645, name: "ram memento", category: "Mog Garden" },
    { id: 2646, name: "sapling memento", category: "Mog Garden" },
    { id: 2647, name: "green foliage treant memento", category: "Mog Garden" },
    { id: 2648, name: "red foliage treant memento", category: "Mog Garden" },
    { id: 2649, name: "baby rabbit memento", category: "Mog Garden" },
    { id: 2650, name: "rabbit memento", category: "Mog Garden" },
    { id: 2651, name: "white rabbit memento", category: "Mog Garden" },
    { id: 2652, name: "baby lizard memento", category: "Mog Garden" },
    { id: 2653, name: "lizard memento", category: "Mog Garden" },
    { id: 2654, name: "alabaster lizard memento", category: "Mog Garden" },
    { id: 2655, name: "baby cockatrice memento", category: "Mog Garden" },
    { id: 2656, name: "cockatrice memento", category: "Mog Garden" },
    { id: 2657, name: "ziz memento", category: "Mog Garden" },
    { id: 2658, name: "baby raptor memento", category: "Mog Garden" },
    { id: 2659, name: "raptor memento", category: "Mog Garden" },
    { id: 2660, name: "red raptor memento", category: "Mog Garden" },
    { id: 2661, name: "baby eft memento", category: "Mog Garden" },
    { id: 2662, name: "eft memento", category: "Mog Garden" },
    { id: 2663, name: "tarichuk memento", category: "Mog Garden" },
    { id: 2664, name: "dhalmel calf memento", category: "Mog Garden" },
    { id: 2665, name: "dhalmel memento", category: "Mog Garden" },
    { id: 2666, name: "great dhalmel memento", category: "Mog Garden" },
    { id: 2667, name: "sea monk larva memento", category: "Mog Garden" },
    { id: 2668, name: "sea monk memento", category: "Mog Garden" },
    { id: 2669, name: "blue sea monk memento", category: "Mog Garden" },
    { id: 2670, name: "uragnite youngling memento", category: "Mog Garden" },
    { id: 2671, name: "uragnite memento", category: "Mog Garden" },
    { id: 2672, name: "limascabra memento", category: "Mog Garden" },
    { id: 2673, name: "immature crab memento", category: "Mog Garden" },
    { id: 2674, name: "crab memento", category: "Mog Garden" },
    { id: 2675, name: "porter crab memento", category: "Mog Garden" },
    { id: 2676, name: "baby colibri memento", category: "Mog Garden" },
    { id: 2677, name: "colibri memento", category: "Mog Garden" },
    { id: 2678, name: "toucalibri memento", category: "Mog Garden" },
    { id: 2679, name: "coeurl cub memento", category: "Mog Garden" },
    { id: 2680, name: "coeurl memento", category: "Mog Garden" },
    { id: 2681, name: "lynx memento", category: "Mog Garden" },
    { id: 2682, name: "buffalo calf memento", category: "Mog Garden" },
    { id: 2683, name: "buffalo memento", category: "Mog Garden" },
    { id: 2684, name: "mini slime memento", category: "Mog Garden" },
    { id: 2685, name: "slime memento", category: "Mog Garden" },
    { id: 2686, name: "clot memento", category: "Mog Garden" },
    { id: 2687, name: "hecteyes memento", category: "Mog Garden" },
    { id: 2688, name: "tiny bugard memento", category: "Mog Garden" },
    { id: 2689, name: "bugard memento", category: "Mog Garden" },
    { id: 2690, name: "abyssobugard memento", category: "Mog Garden" },
    { id: 2691, name: "baby adamantoise memento", category: "Mog Garden" },
    { id: 2692, name: "adamantoise memento", category: "Mog Garden" },
    { id: 2693, name: "great adamantoise memento", category: "Mog Garden" },
    { id: 2694, name: "white adamantoise memento", category: "Mog Garden" },
    { id: 2695, name: "ferromantoise memento", category: "Mog Garden" },
    { id: 2696, name: "great ferromantoise memento", category: "Mog Garden" },
    { id: 2697, name: "cluster memento", category: "Mog Garden" },
    { id: 2698, name: "bomb memento", category: "Mog Garden" },
    { id: 2699, name: "djinn memento", category: "Mog Garden" },
    { id: 2700, name: "snoll memento", category: "Mog Garden" },
    { id: 2701, name: "behemoth cub memento", category: "Mog Garden" },
    { id: 2702, name: "behemoth memento", category: "Mog Garden" },
    { id: 2703, name: "king behemoth memento", category: "Mog Garden" },
    { id: 2704, name: "elasmoth memento", category: "Mog Garden" },
    { id: 2705, name: "skormoth memento", category: "Mog Garden" },
    { id: 2706, name: "dragon hatchling memento", category: "Mog Garden" },
    { id: 2707, name: "wyvern memento", category: "Mog Garden" },
    { id: 2708, name: "blue wyvern memento", category: "Mog Garden" },
    { id: 2709, name: "green wyvern memento", category: "Mog Garden" },
    { id: 2710, name: "abyssal wyrm memento", category: "Mog Garden" },
    { id: 2711, name: "lunar wyrm memento", category: "Mog Garden" },
    { id: 2712, name: "blazing wyrm memento", category: "Mog Garden" },
    { id: 2713, name: "pequetender memento", category: "Mog Garden" },
    { id: 2714, name: "sabotender memento", category: "Mog Garden" },
    { id: 2715, name: "jumbotender memento", category: "Mog Garden" },
    { id: 2790, name: "sheet of conflict tunes", category: "Permanent Key Items" },
    { id: 2791, name: "sheet of Promathia tunes", category: "Permanent Key Items" },
    { id: 2792, name: "sheet of Adoulinian tunes", category: "Permanent Key Items" },
    { id: 2793, name: "\"Sakura and the Fountain\"", category: "Mog Garden" },
    { id: 2826, name: "imperial chair", category: "Permanent Key Items" },
    { id: 2827, name: "decorative chair", category: "Permanent Key Items" },
    { id: 2828, name: "ornate stool", category: "Permanent Key Items" },
    { id: 2829, name: "refined chair", category: "Permanent Key Items" },
    { id: 2830, name: "portable container", category: "Permanent Key Items" },
    { id: 2831, name: "chocobo chair", category: "Permanent Key Items" },
    { id: 2832, name: "Ephramadian throne", category: "Permanent Key Items" },
    { id: 2833, name: "shadow throne", category: "Permanent Key Items" },
    { id: 2834, name: "leaf bench", category: "Permanent Key Items" },
    { id: 2835, name: "astral cube", category: "Permanent Key Items" },
    { id: 2836, name: "chocobo chair II", category: "Permanent Key Items" },
    { id: 2838, name: "\"Sakura and the Magicked Net\"", category: "Mog Garden" },
    { id: 2839, name: "reaper", category: "Geas Fete" },
    { id: 2843, name: "lightsworm", category: "Permanent Key Items" },
    { id: 2844, name: "\"Sakura's Excellent Adventure\"", category: "Mog Garden" },
    { id: 2845, name: "\"Sakura and the Cactus Corps\"", category: "Mog Garden" },
    { id: 2846, name: "\"Sakura and the Holy Grail\"", category: "Mog Garden" },
    { id: 2884, name: "\"Rhapsody in White\"", category: "Permanent Key Items" },
    { id: 2885, name: "\"Rhapsody in Umber\"", category: "Permanent Key Items" },
    { id: 2886, name: "\"Rhapsody in Azure\"", category: "Permanent Key Items" },
    { id: 2887, name: "\"Rhapsody in Crimson\"", category: "Permanent Key Items" },
    { id: 2888, name: "\"Rhapsody in Emerald\"", category: "Permanent Key Items" },
    { id: 2889, name: "\"Rhapsody in Mauve\"", category: "Permanent Key Items" },
    { id: 2890, name: "\"Rhapsody in Fuchsia\"", category: "Permanent Key Items" },
    { id: 2891, name: "\"Rhapsody in Puce\"", category: "Permanent Key Items" },
    { id: 2892, name: "\"Rhapsody in Ochre\"", category: "Permanent Key Items" },
    { id: 2893, name: "\"Scintillating Rhapsody\"", category: "Permanent Key Items" },
    { id: 2894, name: "tribulens", category: "Geas Fete" },
    { id: 2895, name: "Wepwawet's tooth", category: "Geas Fete" },
    { id: 2896, name: "Lydia's vine", category: "Geas Fete" },
    { id: 2897, name: "Aglaophotis bud", category: "Geas Fete" },
    { id: 2898, name: "Tangata's wing", category: "Geas Fete" },
    { id: 2899, name: "Vidala's claw", category: "Geas Fete" },
    { id: 2900, name: "Gestalt's retina", category: "Geas Fete" },
    { id: 2901, name: "Angrboda's necklace", category: "Geas Fete" },
    { id: 2902, name: "Cunnast's talon", category: "Geas Fete" },
    { id: 2903, name: "Revetaur's horn", category: "Geas Fete" },
    { id: 2904, name: "Ferrodon's scale", category: "Geas Fete" },
    { id: 2905, name: "Gulltop's shell", category: "Geas Fete" },
    { id: 2906, name: "Vyala's prey", category: "Geas Fete" },
    { id: 2907, name: "Blazewing's pincer", category: "Geas Fete" },
    { id: 2908, name: "Coven's dust", category: "Geas Fete" },
    { id: 2909, name: "Pazuzu's blade hilt", category: "Geas Fete" },
    { id: 2910, name: "Wrathare's carrot", category: "Geas Fete" },
    { id: 2911, name: "Ionos's webbing", category: "Geas Fete" },
    { id: 2912, name: "Sandy's lasher", category: "Geas Fete" },
    { id: 2913, name: "Nosoi's feather", category: "Geas Fete" },
    { id: 2914, name: "Brittlis's ring", category: "Geas Fete" },
    { id: 2915, name: "Kamohoalii's fin", category: "Geas Fete" },
    { id: 2916, name: "Umdhlebi's flower", category: "Geas Fete" },
    { id: 2917, name: "Fleetstalker's claw", category: "Geas Fete" },
    { id: 2918, name: "Shockmaw's blubber", category: "Geas Fete" },
    { id: 2919, name: "Urmahlullu's armor", category: "Geas Fete" },
    { id: 2920, name: "eschan urn", category: "Geas Fete" },
    { id: 2921, name: "eschan cellar", category: "Geas Fete" },
    { id: 2922, name: "eschan nef", category: "Geas Fete" },
    { id: 2926, name: "\"Card Jailer Teodor\"", category: "Permanent Key Items" },
    { id: 2927, name: "Bia's glove", category: "Geas Fete" },
    { id: 2928, name: "Ruea's stone", category: "Geas Fete" },
    { id: 2929, name: "Ma's lance", category: "Geas Fete" },
    { id: 2930, name: "Khon's scepter", category: "Geas Fete" },
    { id: 2931, name: "Met's ring", category: "Geas Fete" },
    { id: 2932, name: "Khun's crown", category: "Geas Fete" },
    { id: 2933, name: "Wasserspeier's horn", category: "Geas Fete" },
    { id: 2934, name: "Emputa's wing", category: "Geas Fete" },
    { id: 2935, name: "Peirithoos's hoof", category: "Geas Fete" },
    { id: 2936, name: "Asida's gel", category: "Geas Fete" },
    { id: 2937, name: "Tenodera's scythe", category: "Geas Fete" },
    { id: 2938, name: "Sava Savanovic's cape", category: "Geas Fete" },
    { id: 2939, name: "Palila's talon", category: "Geas Fete" },
    { id: 2940, name: "Hanbi's nail", category: "Geas Fete" },
    { id: 2941, name: "Yilan's scale", category: "Geas Fete" },
    { id: 2942, name: "Amymone's tooth", category: "Geas Fete" },
    { id: 2943, name: "Naphula's bracelet", category: "Geas Fete" },
    { id: 2944, name: "Kammavaca's binding", category: "Geas Fete" },
    { id: 2945, name: "Pakecet's blubber", category: "Geas Fete" },
    { id: 2946, name: "Duke Vepar's signet", category: "Geas Fete" },
    { id: 2947, name: "Vir'ava's stalk", category: "Geas Fete" },
    { id: 2948, name: "Byakko's Pride", category: "Geas Fete" },
    { id: 2949, name: "Genbu's Honor", category: "Geas Fete" },
    { id: 2950, name: "Seiryu's Nobility", category: "Geas Fete" },
    { id: 2951, name: "Suzaku's Benefaction", category: "Geas Fete" },
    { id: 2952, name: "Kirin's Fervor", category: "Geas Fete" },
    { id: 2953, name: "Ark Angel HM's coat", category: "Geas Fete" },
    { id: 2954, name: "Ark Angel TT's necklace", category: "Geas Fete" },
    { id: 2955, name: "Ark Angel MR's buckle", category: "Geas Fete" },
    { id: 2956, name: "Ark Angel EV's sash", category: "Geas Fete" },
    { id: 2957, name: "Ark Angel GK's bangle", category: "Geas Fete" },
    { id: 2963, name: "job gesture: geomancer", category: "Permanent Key Items" },
    { id: 2964, name: "job gesture: rune fencer", category: "Permanent Key Items" },
    { id: 2965, name: "golden shovel cordon", category: "Permanent Key Items" },
    { id: 2971, name: "song of hope", category: "Permanent Key Items" },
    { id: 2976, name: "primary nazar", category: "Geas Fete" },
    { id: 2977, name: "secondary nazar", category: "Geas Fete" },
    { id: 2978, name: "tertiary nazar", category: "Geas Fete" },
    { id: 2979, name: "quaternary nazar", category: "Geas Fete" },
    { id: 2980, name: "quinary nazar", category: "Geas Fete" },
    { id: 2981, name: "senary nazar", category: "Geas Fete" },
    { id: 2982, name: "septenary nazar", category: "Geas Fete" },
    { id: 2983, name: "octonary nazar", category: "Geas Fete" },
    { id: 2984, name: "nonary nazar", category: "Geas Fete" },
    { id: 2985, name: "denary nazar", category: "Geas Fete" },
    { id: 2986, name: "primal nazar", category: "Geas Fete" },
    { id: 2989, name: "dimensional compass", category: "Permanent Key Items" },
    { id: 2991, name: "Crom Dubh's helm", category: "Geas Fete" },
    { id: 2992, name: "Golden Kist's key", category: "Geas Fete" },
    { id: 2993, name: "Mauve-wristed Gomberry's knife", category: "Geas Fete" },
    { id: 2994, name: "Dazzling Dolores's vine", category: "Geas Fete" },
    { id: 2995, name: "Taelmoth's staff", category: "Geas Fete" },
    { id: 2996, name: "Belphegor's crown", category: "Geas Fete" },
    { id: 2997, name: "Kabandha's wing", category: "Geas Fete" },
    { id: 2998, name: "Selkit's pincer", category: "Geas Fete" },
    { id: 2999, name: "Sang Buaya's tusk", category: "Geas Fete" },
    { id: 3000, name: "Sabotender Royal's needle", category: "Geas Fete" },
    { id: 3001, name: "Zduhac's talon", category: "Geas Fete" },
    { id: 3002, name: "Oryx's plumage", category: "Geas Fete" },
    { id: 3003, name: "Strophadia's pearl", category: "Geas Fete" },
    { id: 3004, name: "Gajasimha's mane", category: "Geas Fete" },
    { id: 3005, name: "Ironside's maul", category: "Geas Fete" },
    { id: 3006, name: "Sarsaok's hoard", category: "Geas Fete" },
    { id: 3007, name: "Old Shuck's tuft", category: "Geas Fete" },
    { id: 3008, name: "Bashmu's trinket", category: "Geas Fete" },
    { id: 3009, name: "Maju's claw", category: "Geas Fete" },
    { id: 3010, name: "Yakshi's scroll", category: "Geas Fete" },
    { id: 3011, name: "Neak's treasure", category: "Geas Fete" },
    { id: 3012, name: "Teles's hymn", category: "Geas Fete" },
    { id: 3013, name: "Zerde's cup", category: "Geas Fete" },
    { id: 3014, name: "Vinipata's blade", category: "Geas Fete" },
    { id: 3015, name: "Schah's gambit", category: "Geas Fete" },
    { id: 3016, name: "Albumen's flower", category: "Geas Fete" },
    { id: 3017, name: "Onychophora's soil", category: "Geas Fete" },
    { id: 3018, name: "Erinys's beak", category: "Geas Fete" },
    { id: 3026, name: "Phoenix's blessing", category: "Permanent Key Items" },
    { id: 3031, name: "radialens", category: "Geas Fete" },
    { id: 3032, name: "mollifier", category: "Geas Fete" },
    { id: 3051, name: "Mog Patio design document", category: "Permanent Key Items" },
    { id: 3055, name: "trainer's whistle", category: "Mounts" },
    { id: 3069, name: "shimmering invitation", category: "Mog Garden" },
    { id: 3070, name: "Grunt Heard 'Round the World", category: "Permanent Key Items" },
    { id: 3072, name: "♪Chocobo companion", category: "Mounts" },
    { id: 3073, name: "♪Raptor companion", category: "Mounts" },
    { id: 3074, name: "♪Tiger companion", category: "Mounts" },
    { id: 3075, name: "♪Crab companion", category: "Mounts" },
    { id: 3076, name: "♪Red crab companion", category: "Mounts" },
    { id: 3077, name: "♪Bomb companion", category: "Mounts" },
    { id: 3078, name: "♪Sheep companion", category: "Mounts" },
    { id: 3079, name: "♪Morbol companion", category: "Mounts" },
    { id: 3080, name: "♪Crawler companion", category: "Mounts" },
    { id: 3081, name: "♪Fenrir whistle", category: "Mounts" },
    { id: 3082, name: "♪Beetle companion", category: "Mounts" },
    { id: 3083, name: "♪Moogle companion", category: "Mounts" },
    { id: 3084, name: "♪Magic pot companion", category: "Mounts" },
    { id: 3085, name: "♪Tulfaire companion", category: "Mounts" },
    { id: 3086, name: "♪Warmachine companion", category: "Mounts" },
    { id: 3087, name: "♪Xzomit companion", category: "Mounts" },
    { id: 3088, name: "♪Hippogryph companion", category: "Mounts" },
    { id: 3089, name: "♪Spectral chair companion", category: "Mounts" },
    { id: 3090, name: "♪Spheroid companion", category: "Mounts" },
    { id: 3091, name: "♪Omega whistle", category: "Mounts" },
    { id: 3092, name: "♪Coeurl companion", category: "Mounts" },
    { id: 3093, name: "♪Goobbue companion", category: "Mounts" },
    { id: 3094, name: "♪Raaz companion", category: "Mounts" },
    { id: 3095, name: "♪Levitus key", category: "Mounts" },
    { id: 3096, name: "♪Adamantoise companion", category: "Mounts" },
    { id: 3097, name: "♪Dhalmel companion", category: "Mounts" },
    { id: 3098, name: "♪Doll companion", category: "Mounts" },
    { id: 3099, name: "♪Golden Bomb companion", category: "Mounts" },
    { id: 3100, name: "♪Buffalo companion", category: "Mounts" },
    { id: 3101, name: "♪Wivre companion", category: "Mounts" },
    { id: 3102, name: "♪Red Raptor companion", category: "Mounts" },
    { id: 3103, name: "♪Iron Giant companion", category: "Mounts" },
    { id: 3104, name: "♪Byakko", category: "Mounts" },
    { id: 3105, name: "♪Noble Chocobo companion", category: "Mounts" },
    { id: 3106, name: "♪Ixion companion", category: "Mounts" },
    { id: 3107, name: "♪Phuabo companion", category: "Mounts" },
    { id: 3108, name: "♪Craklaw companion", category: "Mounts" },
    { id: 3109, name: "♪Alicorn companion", category: "Mounts" },
    { id: 3110, name: "♪Bubble Crab companion", category: "Mounts" },
    { id: 3138, name: "Ygnas's insignia", category: "Permanent Key Items" },
    { id: 3147, name: "Ygnas's leaf", category: "Permanent Key Items" },
    { id: 3154, name: "reassembling technique", category: "Permanent Key Items" },
    { id: 3156, name: "empty hourglass", category: "Permanent Key Items" },
    { id: 3157, name: "filled memory gem", category: "Permanent Key Items" },
    { id: 3159, name: "Elvaan Mask of Light", category: "Permanent Key Items" },
    { id: 3161, name: "Galka Mask of Light", category: "Permanent Key Items" },
    { id: 3163, name: "Tarutaru Mask of Light", category: "Permanent Key Items" },
    { id: 3165, name: "Mithra Mask of Light", category: "Permanent Key Items" },
    { id: 3191, name: "sheet of Mapitoto tunes", category: "Permanent Key Items" },
    { id: 3192, name: "mandragora sproutling memento", category: "Mog Garden" },
    { id: 3193, name: "mandragora memento", category: "Mog Garden" },
    { id: 3194, name: "elder mandragora memento", category: "Mog Garden" },
    { id: 3195, name: "lycopodium memento", category: "Mog Garden" },
    { id: 3196, name: "ake-ome memento", category: "Mog Garden" },
    { id: 3197, name: "adenium memento", category: "Mog Garden" },
    { id: 3198, name: "elder adenium memento", category: "Mog Garden" },
    { id: 3199, name: "korrigan memento", category: "Mog Garden" },
    { id: 3200, name: "pachypodium memento", category: "Mog Garden" },
    { id: 3201, name: "citrullus memento", category: "Mog Garden" },
    { id: 3224, name: "Primer on Martial Techniques", category: "Permanent Key Items" },
    { id: 3225, name: "Treatise on Martial Techniques", category: "Permanent Key Items" },
    { id: 3226, name: "sheet of Al'Taieu tunes", category: "Permanent Key Items" },
    { id: 3227, name: "sheet of Jeuno tunes", category: "Permanent Key Items" },
    { id: 3228, name: "sheet of harvest tunes", category: "Permanent Key Items" },
    { id: 3237, name: "information on Dealan-dhe", category: "Permanent Key Items" },
    { id: 3238, name: "information on Sgili", category: "Permanent Key Items" },
    { id: 3239, name: "information on U Bnai", category: "Permanent Key Items" },
    { id: 3240, name: "information on Gogmagog", category: "Permanent Key Items" },
    { id: 3241, name: "information on Aristaeus", category: "Permanent Key Items" },
    { id: 3242, name: "information on Marmorkrebs", category: "Permanent Key Items" },
    { id: 3243, name: "information on Gigelorum", category: "Permanent Key Items" },
    { id: 3244, name: "information on Raskovniche", category: "Permanent Key Items" },
    { id: 3245, name: "information on Procne", category: "Permanent Key Items" },
    { id: 3246, name: "information on Henwen", category: "Permanent Key Items" },
    { id: 3247, name: "information on Xevioso", category: "Permanent Key Items" },
    { id: 3248, name: "information on Ngai", category: "Permanent Key Items" },
    { id: 3249, name: "information on Kalunga", category: "Permanent Key Items" },
    { id: 3250, name: "information on Ongo", category: "Permanent Key Items" },
    { id: 3251, name: "information on Mboze", category: "Permanent Key Items" },
    { id: 3252, name: "information on Arebati", category: "Permanent Key Items" },
    { id: 3253, name: "information on Bumba", category: "Permanent Key Items" },
    { id: 3260, name: "Mnejing's receiver", category: "Permanent Key Items" },
    { id: 3262, name: "master breaker", category: "Permanent Key Items" },
    { id: 3268, name: "sheet of ancient tunes", category: "Permanent Key Items" },
    { id: 3270, name: "courageous warrior's shard", category: "Active Effects" },
    { id: 3271, name: "dedicated monk's shard", category: "Active Effects" },
    { id: 3272, name: "stalwart white mage's shard", category: "Active Effects" },
    { id: 3273, name: "storied black mage's shard", category: "Active Effects" },
    { id: 3274, name: "peerless red mage's shard", category: "Active Effects" },
    { id: 3275, name: "refined thief's shard", category: "Active Effects" },
    { id: 3276, name: "elegant paladin's shard", category: "Active Effects" },
    { id: 3277, name: "stoic dark knight's shard", category: "Active Effects" },
    { id: 3278, name: "fervent beastmaster's shard", category: "Active Effects" },
    { id: 3279, name: "distinguished bard's shard", category: "Active Effects" },
    { id: 3280, name: "relentless ranger's shard", category: "Active Effects" },
    { id: 3281, name: "inimitable samurai's shard", category: "Active Effects" },
    { id: 3282, name: "valiant ninja's shard", category: "Active Effects" },
    { id: 3283, name: "heroic dragoon's shard", category: "Active Effects" },
    { id: 3284, name: "learned summoner's shard", category: "Active Effects" },
    { id: 3285, name: "unrivalled blue mage's shard", category: "Active Effects" },
    { id: 3286, name: "unparalleled corsair's shard", category: "Active Effects" },
    { id: 3287, name: "dignified puppetmaster's shard", category: "Active Effects" },
    { id: 3288, name: "graceful dancer's shard", category: "Active Effects" },
    { id: 3289, name: "clever scholar's shard", category: "Active Effects" },
    { id: 3290, name: "dynamic geomancer's shard", category: "Active Effects" },
    { id: 3291, name: "ardent rune fencer's shard", category: "Active Effects" },
    { id: 3292, name: "distorted fragment", category: "Active Effects" },
    { id: 3304, name: "Silver Knife membership card", category: "Permanent Key Items" },
    { id: 3305, name: "courageous warrior's soul", category: "Active Effects" },
    { id: 3306, name: "dedicated monk's soul", category: "Active Effects" },
    { id: 3307, name: "stalwart white mage's soul", category: "Active Effects" },
    { id: 3308, name: "storied black mage's soul", category: "Active Effects" },
    { id: 3309, name: "peerless red mage's soul", category: "Active Effects" },
    { id: 3310, name: "refined thief's soul", category: "Active Effects" },
    { id: 3311, name: "elegant paladin's soul", category: "Active Effects" },
    { id: 3312, name: "stoic dark knight's soul", category: "Active Effects" },
    { id: 3313, name: "fervent beastmaster's soul", category: "Active Effects" },
    { id: 3314, name: "distinguished bard's soul", category: "Active Effects" },
    { id: 3315, name: "relentless ranger's soul", category: "Active Effects" },
    { id: 3316, name: "inimitable samurai's soul", category: "Active Effects" },
    { id: 3317, name: "valiant ninja's soul", category: "Active Effects" },
    { id: 3318, name: "heroic dragoon's soul", category: "Active Effects" },
    { id: 3319, name: "learned summoner's soul", category: "Active Effects" },
    { id: 3320, name: "unrivalled blue mage's soul", category: "Active Effects" },
    { id: 3321, name: "unparalleled corsair's soul", category: "Active Effects" },
    { id: 3322, name: "dignified puppetmaster's soul", category: "Active Effects" },
    { id: 3323, name: "graceful dancer's soul", category: "Active Effects" },
    { id: 3324, name: "clever scholar's soul", category: "Active Effects" },
    { id: 3325, name: "dynamic geomancer's soul", category: "Active Effects" },
    { id: 3326, name: "ardent rune fencer's soul", category: "Active Effects" },
    { id: 3327, name: "Uran-Mafran's orb", category: "Permanent Key Items" },
    { id: 3328, name: "Ruspix's plate", category: "Permanent Key Items" },
    { id: 3329, name: "sheet of ancient battle tunes", category: "Permanent Key Items" },
    { id: 3330, name: "sheet of Destiny Destroyer tunes", category: "Permanent Key Items" },
    { id: 3331, name: "sheet of character selection tunes", category: "Permanent Key Items" },
    { id: 3332, name: "sheet of Starlight tunes", category: "Permanent Key Items" },
    { id: 3339, name: "vial of Chaos's blood", category: "Permanent Key Items" },
    { id: 3343, name: "adenium bench", category: "Permanent Key Items" },
    { id: 3344, name: "sheet of chocobo tunes", category: "Permanent Key Items" },
    { id: 3350, name: "sheet of Near East tunes", category: "Permanent Key Items" },
    { id: 3358, name: "Apollyon verification key", category: "Permanent Key Items" },
    { id: 3359, name: "Temenos verification key", category: "Permanent Key Items" },
    { id: 3360, name: "sheet of divine tunes", category: "Permanent Key Items" },
    { id: 3361, name: "cipher bracelet", category: "Permanent Key Items" },
    { id: 3363, name: "sheet of fishing tunes", category: "Permanent Key Items" },
    { id: 3364, name: "Delineated Grace", category: "Permanent Key Items" },
    { id: 3365, name: "Angelic Grace", category: "Permanent Key Items" },
    { id: 3366, name: "Vital Grace", category: "Permanent Key Items" },
]

const KI_BY_ID = new Map<number, KeyItemCatalogEntry>(KEY_ITEMS.map(k => [k.id, k]))

export function lookupKeyItem(id: number): KeyItemCatalogEntry {
    const found = KI_BY_ID.get(id)
    if (found) return found
    return { id, name: `Key Item #${id}`, category: 'Permanent Key Items' }
}
