// Spell catalog for Vanalytics's Spells + Trusts tabs.
//
// Source: Windower's Resources/resources_data/spells.lua (canonical FFXI
// spell list with names, types, MP costs, and per-job level requirements).
// Exclusions: XIchecklist's maps/spells_exclusions.lua (removes unlearnable
// spells like Dia IV/V, certain bard songs, retired trusts).
//
// Trusts are stored as type='Trust'. Both the Spells tab (filtered) and
// the Trusts tab (full list) draw from this single catalog.
//
// Generated via one-shot bash/awk pipeline; regenerate when Windower
// pushes new spells.

export interface SpellCatalogEntry {
    id: number
    name: string
    type: SpellType
    mpCost: number
    /** Lowest job-level requirement across all jobs that can cast this spell.
     *  0 for trusts (no level gate). */
    minLevel: number
}

export type SpellType =
    | 'WhiteMagic'
    | 'BlackMagic'
    | 'SummonerPact'
    | 'Ninjutsu'
    | 'BardSong'
    | 'BlueMagic'
    | 'Geomancy'
    | 'Trust'

export const SPELL_TYPE_LABELS: Record<SpellType, string> = {
    WhiteMagic: 'White Magic',
    BlackMagic: 'Black Magic',
    SummonerPact: 'Summoner Pact',
    Ninjutsu: 'Ninjutsu',
    BardSong: 'Bard Song',
    BlueMagic: 'Blue Magic',
    Geomancy: 'Geomancy',
    Trust: 'Trust',
}

export const SPELLS: SpellCatalogEntry[] = [
    { id: 1, name: "Cure", type: "WhiteMagic", mpCost: 8, minLevel: 1 },
    { id: 2, name: "Cure II", type: "WhiteMagic", mpCost: 24, minLevel: 11 },
    { id: 3, name: "Cure III", type: "WhiteMagic", mpCost: 46, minLevel: 21 },
    { id: 4, name: "Cure IV", type: "WhiteMagic", mpCost: 88, minLevel: 41 },
    { id: 5, name: "Cure V", type: "WhiteMagic", mpCost: 135, minLevel: 61 },
    { id: 6, name: "Cure VI", type: "WhiteMagic", mpCost: 227, minLevel: 80 },
    { id: 7, name: "Curaga", type: "WhiteMagic", mpCost: 60, minLevel: 16 },
    { id: 8, name: "Curaga II", type: "WhiteMagic", mpCost: 120, minLevel: 31 },
    { id: 9, name: "Curaga III", type: "WhiteMagic", mpCost: 180, minLevel: 51 },
    { id: 10, name: "Curaga IV", type: "WhiteMagic", mpCost: 260, minLevel: 71 },
    { id: 11, name: "Curaga V", type: "WhiteMagic", mpCost: 380, minLevel: 91 },
    { id: 12, name: "Raise", type: "WhiteMagic", mpCost: 150, minLevel: 25 },
    { id: 13, name: "Raise II", type: "WhiteMagic", mpCost: 150, minLevel: 56 },
    { id: 14, name: "Poisona", type: "WhiteMagic", mpCost: 8, minLevel: 6 },
    { id: 15, name: "Paralyna", type: "WhiteMagic", mpCost: 12, minLevel: 9 },
    { id: 16, name: "Blindna", type: "WhiteMagic", mpCost: 16, minLevel: 14 },
    { id: 17, name: "Silena", type: "WhiteMagic", mpCost: 24, minLevel: 19 },
    { id: 18, name: "Stona", type: "WhiteMagic", mpCost: 40, minLevel: 39 },
    { id: 19, name: "Viruna", type: "WhiteMagic", mpCost: 48, minLevel: 34 },
    { id: 20, name: "Cursna", type: "WhiteMagic", mpCost: 30, minLevel: 29 },
    { id: 21, name: "Holy", type: "WhiteMagic", mpCost: 100, minLevel: 50 },
    { id: 22, name: "Holy II", type: "WhiteMagic", mpCost: 150, minLevel: 95 },
    { id: 23, name: "Dia", type: "WhiteMagic", mpCost: 7, minLevel: 1 },
    { id: 24, name: "Dia II", type: "WhiteMagic", mpCost: 30, minLevel: 31 },
    { id: 25, name: "Dia III", type: "WhiteMagic", mpCost: 45, minLevel: 75 },
    { id: 28, name: "Banish", type: "WhiteMagic", mpCost: 15, minLevel: 5 },
    { id: 29, name: "Banish II", type: "WhiteMagic", mpCost: 57, minLevel: 30 },
    { id: 30, name: "Banish III", type: "WhiteMagic", mpCost: 96, minLevel: 65 },
    { id: 31, name: "Banish IV", type: "WhiteMagic", mpCost: 108, minLevel: 90 },
    { id: 32, name: "Banish V", type: "WhiteMagic", mpCost: 159, minLevel: 0 },
    { id: 33, name: "Diaga", type: "WhiteMagic", mpCost: 12, minLevel: 15 },
    { id: 34, name: "Diaga II", type: "WhiteMagic", mpCost: 60, minLevel: 45 },
    { id: 35, name: "Diaga III", type: "WhiteMagic", mpCost: 120, minLevel: 75 },
    { id: 36, name: "Diaga IV", type: "WhiteMagic", mpCost: 180, minLevel: 0 },
    { id: 37, name: "Diaga V", type: "WhiteMagic", mpCost: 240, minLevel: 0 },
    { id: 38, name: "Banishga", type: "WhiteMagic", mpCost: 41, minLevel: 15 },
    { id: 39, name: "Banishga II", type: "WhiteMagic", mpCost: 120, minLevel: 40 },
    { id: 40, name: "Banishga III", type: "WhiteMagic", mpCost: 233, minLevel: 65 },
    { id: 41, name: "Banishga IV", type: "WhiteMagic", mpCost: 380, minLevel: 0 },
    { id: 42, name: "Banishga V", type: "WhiteMagic", mpCost: 563, minLevel: 0 },
    { id: 43, name: "Protect", type: "WhiteMagic", mpCost: 9, minLevel: 7 },
    { id: 44, name: "Protect II", type: "WhiteMagic", mpCost: 28, minLevel: 27 },
    { id: 45, name: "Protect III", type: "WhiteMagic", mpCost: 46, minLevel: 47 },
    { id: 46, name: "Protect IV", type: "WhiteMagic", mpCost: 65, minLevel: 63 },
    { id: 47, name: "Protect V", type: "WhiteMagic", mpCost: 84, minLevel: 76 },
    { id: 48, name: "Shell", type: "WhiteMagic", mpCost: 18, minLevel: 10 },
    { id: 49, name: "Shell II", type: "WhiteMagic", mpCost: 37, minLevel: 30 },
    { id: 50, name: "Shell III", type: "WhiteMagic", mpCost: 56, minLevel: 50 },
    { id: 51, name: "Shell IV", type: "WhiteMagic", mpCost: 75, minLevel: 68 },
    { id: 52, name: "Shell V", type: "WhiteMagic", mpCost: 93, minLevel: 76 },
    { id: 53, name: "Blink", type: "WhiteMagic", mpCost: 20, minLevel: 19 },
    { id: 54, name: "Stoneskin", type: "WhiteMagic", mpCost: 29, minLevel: 28 },
    { id: 55, name: "Aquaveil", type: "WhiteMagic", mpCost: 12, minLevel: 10 },
    { id: 56, name: "Slow", type: "WhiteMagic", mpCost: 15, minLevel: 13 },
    { id: 57, name: "Haste", type: "WhiteMagic", mpCost: 40, minLevel: 40 },
    { id: 58, name: "Paralyze", type: "WhiteMagic", mpCost: 6, minLevel: 4 },
    { id: 59, name: "Silence", type: "WhiteMagic", mpCost: 16, minLevel: 15 },
    { id: 60, name: "Barfire", type: "WhiteMagic", mpCost: 6, minLevel: 16 },
    { id: 61, name: "Barblizzard", type: "WhiteMagic", mpCost: 6, minLevel: 20 },
    { id: 62, name: "Baraero", type: "WhiteMagic", mpCost: 6, minLevel: 12 },
    { id: 63, name: "Barstone", type: "WhiteMagic", mpCost: 6, minLevel: 4 },
    { id: 64, name: "Barthunder", type: "WhiteMagic", mpCost: 6, minLevel: 24 },
    { id: 65, name: "Barwater", type: "WhiteMagic", mpCost: 6, minLevel: 8 },
    { id: 66, name: "Barfira", type: "WhiteMagic", mpCost: 12, minLevel: 17 },
    { id: 67, name: "Barblizzara", type: "WhiteMagic", mpCost: 12, minLevel: 21 },
    { id: 68, name: "Baraera", type: "WhiteMagic", mpCost: 12, minLevel: 13 },
    { id: 69, name: "Barstonra", type: "WhiteMagic", mpCost: 12, minLevel: 5 },
    { id: 70, name: "Barthundra", type: "WhiteMagic", mpCost: 12, minLevel: 25 },
    { id: 71, name: "Barwatera", type: "WhiteMagic", mpCost: 12, minLevel: 9 },
    { id: 72, name: "Barsleep", type: "WhiteMagic", mpCost: 7, minLevel: 6 },
    { id: 73, name: "Barpoison", type: "WhiteMagic", mpCost: 9, minLevel: 9 },
    { id: 74, name: "Barparalyze", type: "WhiteMagic", mpCost: 11, minLevel: 11 },
    { id: 75, name: "Barblind", type: "WhiteMagic", mpCost: 13, minLevel: 17 },
    { id: 76, name: "Barsilence", type: "WhiteMagic", mpCost: 15, minLevel: 22 },
    { id: 77, name: "Barpetrify", type: "WhiteMagic", mpCost: 20, minLevel: 42 },
    { id: 78, name: "Barvirus", type: "WhiteMagic", mpCost: 25, minLevel: 38 },
    { id: 79, name: "Slow II", type: "WhiteMagic", mpCost: 45, minLevel: 75 },
    { id: 80, name: "Paralyze II", type: "WhiteMagic", mpCost: 36, minLevel: 75 },
    { id: 81, name: "Recall-Jugner", type: "WhiteMagic", mpCost: 125, minLevel: 53 },
    { id: 82, name: "Recall-Pashh", type: "WhiteMagic", mpCost: 125, minLevel: 53 },
    { id: 83, name: "Recall-Meriph", type: "WhiteMagic", mpCost: 125, minLevel: 53 },
    { id: 84, name: "Baramnesia", type: "WhiteMagic", mpCost: 30, minLevel: 76 },
    { id: 85, name: "Baramnesra", type: "WhiteMagic", mpCost: 60, minLevel: 78 },
    { id: 86, name: "Barsleepra", type: "WhiteMagic", mpCost: 14, minLevel: 7 },
    { id: 87, name: "Barpoisonra", type: "WhiteMagic", mpCost: 18, minLevel: 10 },
    { id: 88, name: "Barparalyzra", type: "WhiteMagic", mpCost: 22, minLevel: 12 },
    { id: 89, name: "Barblindra", type: "WhiteMagic", mpCost: 26, minLevel: 18 },
    { id: 90, name: "Barsilencera", type: "WhiteMagic", mpCost: 30, minLevel: 23 },
    { id: 91, name: "Barpetra", type: "WhiteMagic", mpCost: 40, minLevel: 43 },
    { id: 92, name: "Barvira", type: "WhiteMagic", mpCost: 50, minLevel: 39 },
    { id: 93, name: "Cura", type: "WhiteMagic", mpCost: 30, minLevel: 40 },
    { id: 94, name: "Sacrifice", type: "WhiteMagic", mpCost: 18, minLevel: 65 },
    { id: 95, name: "Esuna", type: "WhiteMagic", mpCost: 24, minLevel: 61 },
    { id: 96, name: "Auspice", type: "WhiteMagic", mpCost: 48, minLevel: 55 },
    { id: 97, name: "Reprisal", type: "WhiteMagic", mpCost: 24, minLevel: 61 },
    { id: 98, name: "Repose", type: "WhiteMagic", mpCost: 26, minLevel: 48 },
    { id: 99, name: "Sandstorm", type: "WhiteMagic", mpCost: 30, minLevel: 41 },
    { id: 100, name: "Enfire", type: "WhiteMagic", mpCost: 12, minLevel: 24 },
    { id: 101, name: "Enblizzard", type: "WhiteMagic", mpCost: 12, minLevel: 22 },
    { id: 102, name: "Enaero", type: "WhiteMagic", mpCost: 12, minLevel: 20 },
    { id: 103, name: "Enstone", type: "WhiteMagic", mpCost: 12, minLevel: 18 },
    { id: 104, name: "Enthunder", type: "WhiteMagic", mpCost: 12, minLevel: 16 },
    { id: 105, name: "Enwater", type: "WhiteMagic", mpCost: 12, minLevel: 27 },
    { id: 106, name: "Phalanx", type: "WhiteMagic", mpCost: 21, minLevel: 33 },
    { id: 107, name: "Phalanx II", type: "WhiteMagic", mpCost: 42, minLevel: 75 },
    { id: 108, name: "Regen", type: "WhiteMagic", mpCost: 15, minLevel: 18 },
    { id: 109, name: "Refresh", type: "WhiteMagic", mpCost: 40, minLevel: 41 },
    { id: 110, name: "Regen II", type: "WhiteMagic", mpCost: 36, minLevel: 37 },
    { id: 111, name: "Regen III", type: "WhiteMagic", mpCost: 64, minLevel: 59 },
    { id: 112, name: "Flash", type: "WhiteMagic", mpCost: 25, minLevel: 37 },
    { id: 113, name: "Rainstorm", type: "WhiteMagic", mpCost: 30, minLevel: 42 },
    { id: 114, name: "Windstorm", type: "WhiteMagic", mpCost: 30, minLevel: 43 },
    { id: 115, name: "Firestorm", type: "WhiteMagic", mpCost: 30, minLevel: 44 },
    { id: 116, name: "Hailstorm", type: "WhiteMagic", mpCost: 30, minLevel: 45 },
    { id: 117, name: "Thunderstorm", type: "WhiteMagic", mpCost: 30, minLevel: 46 },
    { id: 118, name: "Voidstorm", type: "WhiteMagic", mpCost: 30, minLevel: 47 },
    { id: 119, name: "Aurorastorm", type: "WhiteMagic", mpCost: 30, minLevel: 48 },
    { id: 120, name: "Teleport-Yhoat", type: "WhiteMagic", mpCost: 100, minLevel: 38 },
    { id: 121, name: "Teleport-Altep", type: "WhiteMagic", mpCost: 100, minLevel: 38 },
    { id: 122, name: "Teleport-Holla", type: "WhiteMagic", mpCost: 75, minLevel: 36 },
    { id: 123, name: "Teleport-Dem", type: "WhiteMagic", mpCost: 75, minLevel: 36 },
    { id: 124, name: "Teleport-Mea", type: "WhiteMagic", mpCost: 75, minLevel: 36 },
    { id: 125, name: "Protectra", type: "WhiteMagic", mpCost: 9, minLevel: 7 },
    { id: 126, name: "Protectra II", type: "WhiteMagic", mpCost: 28, minLevel: 27 },
    { id: 127, name: "Protectra III", type: "WhiteMagic", mpCost: 46, minLevel: 47 },
    { id: 128, name: "Protectra IV", type: "WhiteMagic", mpCost: 65, minLevel: 63 },
    { id: 129, name: "Protectra V", type: "WhiteMagic", mpCost: 84, minLevel: 75 },
    { id: 130, name: "Shellra", type: "WhiteMagic", mpCost: 18, minLevel: 17 },
    { id: 131, name: "Shellra II", type: "WhiteMagic", mpCost: 37, minLevel: 37 },
    { id: 132, name: "Shellra III", type: "WhiteMagic", mpCost: 56, minLevel: 57 },
    { id: 133, name: "Shellra IV", type: "WhiteMagic", mpCost: 75, minLevel: 68 },
    { id: 134, name: "Shellra V", type: "WhiteMagic", mpCost: 93, minLevel: 75 },
    { id: 135, name: "Reraise", type: "WhiteMagic", mpCost: 150, minLevel: 25 },
    { id: 136, name: "Invisible", type: "WhiteMagic", mpCost: 15, minLevel: 25 },
    { id: 137, name: "Sneak", type: "WhiteMagic", mpCost: 12, minLevel: 20 },
    { id: 138, name: "Deodorize", type: "WhiteMagic", mpCost: 10, minLevel: 15 },
    { id: 139, name: "Teleport-Vahzl", type: "WhiteMagic", mpCost: 100, minLevel: 42 },
    { id: 140, name: "Raise III", type: "WhiteMagic", mpCost: 150, minLevel: 70 },
    { id: 141, name: "Reraise II", type: "WhiteMagic", mpCost: 150, minLevel: 56 },
    { id: 142, name: "Reraise III", type: "WhiteMagic", mpCost: 150, minLevel: 70 },
    { id: 143, name: "Erase", type: "WhiteMagic", mpCost: 18, minLevel: 32 },
    { id: 144, name: "Fire", type: "BlackMagic", mpCost: 7, minLevel: 13 },
    { id: 145, name: "Fire II", type: "BlackMagic", mpCost: 26, minLevel: 38 },
    { id: 146, name: "Fire III", type: "BlackMagic", mpCost: 63, minLevel: 62 },
    { id: 147, name: "Fire IV", type: "BlackMagic", mpCost: 135, minLevel: 73 },
    { id: 148, name: "Fire V", type: "BlackMagic", mpCost: 228, minLevel: 86 },
    { id: 149, name: "Blizzard", type: "BlackMagic", mpCost: 8, minLevel: 17 },
    { id: 150, name: "Blizzard II", type: "BlackMagic", mpCost: 31, minLevel: 42 },
    { id: 151, name: "Blizzard III", type: "BlackMagic", mpCost: 75, minLevel: 64 },
    { id: 152, name: "Blizzard IV", type: "BlackMagic", mpCost: 162, minLevel: 74 },
    { id: 153, name: "Blizzard V", type: "BlackMagic", mpCost: 267, minLevel: 89 },
    { id: 154, name: "Aero", type: "BlackMagic", mpCost: 6, minLevel: 9 },
    { id: 155, name: "Aero II", type: "BlackMagic", mpCost: 22, minLevel: 34 },
    { id: 156, name: "Aero III", type: "BlackMagic", mpCost: 54, minLevel: 59 },
    { id: 157, name: "Aero IV", type: "BlackMagic", mpCost: 115, minLevel: 72 },
    { id: 158, name: "Aero V", type: "BlackMagic", mpCost: 198, minLevel: 83 },
    { id: 159, name: "Stone", type: "BlackMagic", mpCost: 4, minLevel: 1 },
    { id: 160, name: "Stone II", type: "BlackMagic", mpCost: 16, minLevel: 26 },
    { id: 161, name: "Stone III", type: "BlackMagic", mpCost: 40, minLevel: 51 },
    { id: 162, name: "Stone IV", type: "BlackMagic", mpCost: 88, minLevel: 68 },
    { id: 163, name: "Stone V", type: "BlackMagic", mpCost: 156, minLevel: 77 },
    { id: 164, name: "Thunder", type: "BlackMagic", mpCost: 9, minLevel: 21 },
    { id: 165, name: "Thunder II", type: "BlackMagic", mpCost: 37, minLevel: 46 },
    { id: 166, name: "Thunder III", type: "BlackMagic", mpCost: 91, minLevel: 66 },
    { id: 167, name: "Thunder IV", type: "BlackMagic", mpCost: 195, minLevel: 75 },
    { id: 168, name: "Thunder V", type: "BlackMagic", mpCost: 306, minLevel: 92 },
    { id: 169, name: "Water", type: "BlackMagic", mpCost: 5, minLevel: 5 },
    { id: 170, name: "Water II", type: "BlackMagic", mpCost: 19, minLevel: 30 },
    { id: 171, name: "Water III", type: "BlackMagic", mpCost: 46, minLevel: 55 },
    { id: 172, name: "Water IV", type: "BlackMagic", mpCost: 99, minLevel: 70 },
    { id: 173, name: "Water V", type: "BlackMagic", mpCost: 175, minLevel: 80 },
    { id: 174, name: "Firaga", type: "BlackMagic", mpCost: 57, minLevel: 28 },
    { id: 175, name: "Firaga II", type: "BlackMagic", mpCost: 153, minLevel: 53 },
    { id: 176, name: "Firaga III", type: "BlackMagic", mpCost: 263, minLevel: 69 },
    { id: 177, name: "Firaga IV", type: "BlackMagic", mpCost: 360, minLevel: 0 },
    { id: 178, name: "Firaga V", type: "BlackMagic", mpCost: 450, minLevel: 0 },
    { id: 179, name: "Blizzaga", type: "BlackMagic", mpCost: 80, minLevel: 32 },
    { id: 180, name: "Blizzaga II", type: "BlackMagic", mpCost: 175, minLevel: 57 },
    { id: 181, name: "Blizzaga III", type: "BlackMagic", mpCost: 297, minLevel: 71 },
    { id: 182, name: "Blizzaga IV", type: "BlackMagic", mpCost: 403, minLevel: 0 },
    { id: 183, name: "Blizzaga V", type: "BlackMagic", mpCost: 500, minLevel: 0 },
    { id: 184, name: "Aeroga", type: "BlackMagic", mpCost: 45, minLevel: 23 },
    { id: 185, name: "Aeroga II", type: "BlackMagic", mpCost: 131, minLevel: 48 },
    { id: 186, name: "Aeroga III", type: "BlackMagic", mpCost: 232, minLevel: 67 },
    { id: 187, name: "Aeroga IV", type: "BlackMagic", mpCost: 318, minLevel: 0 },
    { id: 188, name: "Aeroga V", type: "BlackMagic", mpCost: 402, minLevel: 0 },
    { id: 189, name: "Stonega", type: "BlackMagic", mpCost: 24, minLevel: 15 },
    { id: 190, name: "Stonega II", type: "BlackMagic", mpCost: 93, minLevel: 40 },
    { id: 191, name: "Stonega III", type: "BlackMagic", mpCost: 175, minLevel: 63 },
    { id: 192, name: "Stonega IV", type: "BlackMagic", mpCost: 243, minLevel: 0 },
    { id: 193, name: "Stonega V", type: "BlackMagic", mpCost: 315, minLevel: 0 },
    { id: 194, name: "Thundaga", type: "BlackMagic", mpCost: 105, minLevel: 36 },
    { id: 195, name: "Thundaga II", type: "BlackMagic", mpCost: 200, minLevel: 61 },
    { id: 196, name: "Thundaga III", type: "BlackMagic", mpCost: 332, minLevel: 73 },
    { id: 197, name: "Thundaga IV", type: "BlackMagic", mpCost: 450, minLevel: 0 },
    { id: 198, name: "Thundaga V", type: "BlackMagic", mpCost: 520, minLevel: 0 },
    { id: 199, name: "Waterga", type: "BlackMagic", mpCost: 34, minLevel: 19 },
    { id: 200, name: "Waterga II", type: "BlackMagic", mpCost: 112, minLevel: 44 },
    { id: 201, name: "Waterga III", type: "BlackMagic", mpCost: 202, minLevel: 65 },
    { id: 202, name: "Waterga IV", type: "BlackMagic", mpCost: 280, minLevel: 0 },
    { id: 203, name: "Waterga V", type: "BlackMagic", mpCost: 357, minLevel: 0 },
    { id: 204, name: "Flare", type: "BlackMagic", mpCost: 315, minLevel: 60 },
    { id: 205, name: "Flare II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 206, name: "Freeze", type: "BlackMagic", mpCost: 315, minLevel: 50 },
    { id: 207, name: "Freeze II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 208, name: "Tornado", type: "BlackMagic", mpCost: 315, minLevel: 52 },
    { id: 209, name: "Tornado II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 210, name: "Quake", type: "BlackMagic", mpCost: 315, minLevel: 54 },
    { id: 211, name: "Quake II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 212, name: "Burst", type: "BlackMagic", mpCost: 315, minLevel: 56 },
    { id: 213, name: "Burst II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 214, name: "Flood", type: "BlackMagic", mpCost: 315, minLevel: 58 },
    { id: 215, name: "Flood II", type: "BlackMagic", mpCost: 280, minLevel: 75 },
    { id: 216, name: "Gravity", type: "BlackMagic", mpCost: 24, minLevel: 21 },
    { id: 217, name: "Gravity II", type: "BlackMagic", mpCost: 36, minLevel: 98 },
    { id: 218, name: "Meteor", type: "BlackMagic", mpCost: 418, minLevel: 99 },
    { id: 219, name: "Comet", type: "BlackMagic", mpCost: 350, minLevel: 94 },
    { id: 220, name: "Poison", type: "BlackMagic", mpCost: 5, minLevel: 3 },
    { id: 221, name: "Poison II", type: "BlackMagic", mpCost: 38, minLevel: 43 },
    { id: 222, name: "Poison III", type: "BlackMagic", mpCost: 72, minLevel: 0 },
    { id: 223, name: "Poison IV", type: "BlackMagic", mpCost: 106, minLevel: 0 },
    { id: 224, name: "Poison V", type: "BlackMagic", mpCost: 140, minLevel: 0 },
    { id: 225, name: "Poisonga", type: "BlackMagic", mpCost: 44, minLevel: 24 },
    { id: 226, name: "Poisonga II", type: "BlackMagic", mpCost: 112, minLevel: 64 },
    { id: 227, name: "Poisonga III", type: "BlackMagic", mpCost: 180, minLevel: 0 },
    { id: 228, name: "Poisonga IV", type: "BlackMagic", mpCost: 248, minLevel: 0 },
    { id: 229, name: "Poisonga V", type: "BlackMagic", mpCost: 314, minLevel: 0 },
    { id: 230, name: "Bio", type: "BlackMagic", mpCost: 15, minLevel: 10 },
    { id: 231, name: "Bio II", type: "BlackMagic", mpCost: 36, minLevel: 35 },
    { id: 232, name: "Bio III", type: "BlackMagic", mpCost: 54, minLevel: 75 },
    { id: 233, name: "Bio IV", type: "BlackMagic", mpCost: 154, minLevel: 0 },
    { id: 234, name: "Bio V", type: "BlackMagic", mpCost: 197, minLevel: 0 },
    { id: 235, name: "Burn", type: "BlackMagic", mpCost: 25, minLevel: 24 },
    { id: 236, name: "Frost", type: "BlackMagic", mpCost: 25, minLevel: 22 },
    { id: 237, name: "Choke", type: "BlackMagic", mpCost: 25, minLevel: 20 },
    { id: 238, name: "Rasp", type: "BlackMagic", mpCost: 25, minLevel: 18 },
    { id: 239, name: "Shock", type: "BlackMagic", mpCost: 25, minLevel: 16 },
    { id: 240, name: "Drown", type: "BlackMagic", mpCost: 25, minLevel: 27 },
    { id: 241, name: "Retrace", type: "BlackMagic", mpCost: 150, minLevel: 55 },
    { id: 242, name: "Absorb-ACC", type: "BlackMagic", mpCost: 33, minLevel: 61 },
    { id: 243, name: "Absorb-Attri", type: "BlackMagic", mpCost: 33, minLevel: 91 },
    { id: 244, name: "Meteor II", type: "BlackMagic", mpCost: 150, minLevel: 75 },
    { id: 245, name: "Drain", type: "BlackMagic", mpCost: 21, minLevel: 10 },
    { id: 246, name: "Drain II", type: "BlackMagic", mpCost: 37, minLevel: 62 },
    { id: 247, name: "Aspir", type: "BlackMagic", mpCost: 10, minLevel: 20 },
    { id: 248, name: "Aspir II", type: "BlackMagic", mpCost: 5, minLevel: 78 },
    { id: 249, name: "Blaze Spikes", type: "BlackMagic", mpCost: 8, minLevel: 10 },
    { id: 250, name: "Ice Spikes", type: "BlackMagic", mpCost: 16, minLevel: 20 },
    { id: 251, name: "Shock Spikes", type: "BlackMagic", mpCost: 24, minLevel: 30 },
    { id: 252, name: "Stun", type: "BlackMagic", mpCost: 25, minLevel: 37 },
    { id: 253, name: "Sleep", type: "BlackMagic", mpCost: 19, minLevel: 20 },
    { id: 254, name: "Blind", type: "BlackMagic", mpCost: 5, minLevel: 4 },
    { id: 255, name: "Break", type: "BlackMagic", mpCost: 39, minLevel: 85 },
    { id: 256, name: "Virus", type: "BlackMagic", mpCost: 10, minLevel: 1 },
    { id: 257, name: "Curse", type: "BlackMagic", mpCost: 10, minLevel: 1 },
    { id: 258, name: "Bind", type: "BlackMagic", mpCost: 8, minLevel: 7 },
    { id: 259, name: "Sleep II", type: "BlackMagic", mpCost: 29, minLevel: 41 },
    { id: 260, name: "Dispel", type: "BlackMagic", mpCost: 25, minLevel: 32 },
    { id: 261, name: "Warp", type: "BlackMagic", mpCost: 100, minLevel: 17 },
    { id: 262, name: "Warp II", type: "BlackMagic", mpCost: 150, minLevel: 40 },
    { id: 263, name: "Escape", type: "BlackMagic", mpCost: 125, minLevel: 29 },
    { id: 264, name: "Tractor", type: "BlackMagic", mpCost: 26, minLevel: 25 },
    { id: 265, name: "Tractor II", type: "BlackMagic", mpCost: 50, minLevel: 0 },
    { id: 266, name: "Absorb-STR", type: "BlackMagic", mpCost: 33, minLevel: 43 },
    { id: 267, name: "Absorb-DEX", type: "BlackMagic", mpCost: 33, minLevel: 41 },
    { id: 268, name: "Absorb-VIT", type: "BlackMagic", mpCost: 33, minLevel: 35 },
    { id: 269, name: "Absorb-AGI", type: "BlackMagic", mpCost: 33, minLevel: 37 },
    { id: 270, name: "Absorb-INT", type: "BlackMagic", mpCost: 33, minLevel: 39 },
    { id: 271, name: "Absorb-MND", type: "BlackMagic", mpCost: 33, minLevel: 31 },
    { id: 272, name: "Absorb-CHR", type: "BlackMagic", mpCost: 33, minLevel: 33 },
    { id: 273, name: "Sleepga", type: "BlackMagic", mpCost: 38, minLevel: 31 },
    { id: 274, name: "Sleepga II", type: "BlackMagic", mpCost: 58, minLevel: 56 },
    { id: 275, name: "Absorb-TP", type: "BlackMagic", mpCost: 33, minLevel: 45 },
    { id: 276, name: "Blind II", type: "BlackMagic", mpCost: 31, minLevel: 75 },
    { id: 277, name: "Dread Spikes", type: "BlackMagic", mpCost: 78, minLevel: 71 },
    { id: 278, name: "Geohelix", type: "BlackMagic", mpCost: 26, minLevel: 18 },
    { id: 279, name: "Hydrohelix", type: "BlackMagic", mpCost: 26, minLevel: 20 },
    { id: 280, name: "Anemohelix", type: "BlackMagic", mpCost: 26, minLevel: 22 },
    { id: 281, name: "Pyrohelix", type: "BlackMagic", mpCost: 26, minLevel: 24 },
    { id: 282, name: "Cryohelix", type: "BlackMagic", mpCost: 26, minLevel: 26 },
    { id: 283, name: "Ionohelix", type: "BlackMagic", mpCost: 26, minLevel: 28 },
    { id: 284, name: "Noctohelix", type: "BlackMagic", mpCost: 26, minLevel: 30 },
    { id: 285, name: "Luminohelix", type: "BlackMagic", mpCost: 26, minLevel: 32 },
    { id: 286, name: "Addle", type: "WhiteMagic", mpCost: 36, minLevel: 83 },
    { id: 287, name: "Klimaform", type: "BlackMagic", mpCost: 30, minLevel: 46 },
    { id: 288, name: "Fire Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 289, name: "Ice Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 290, name: "Air Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 291, name: "Earth Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 292, name: "Thunder Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 293, name: "Water Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 294, name: "Light Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 295, name: "Dark Spirit", type: "SummonerPact", mpCost: 10, minLevel: 1 },
    { id: 296, name: "Carbuncle", type: "SummonerPact", mpCost: 5, minLevel: 1 },
    { id: 297, name: "Fenrir", type: "SummonerPact", mpCost: 15, minLevel: 1 },
    { id: 298, name: "Ifrit", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 299, name: "Titan", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 300, name: "Leviathan", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 301, name: "Garuda", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 302, name: "Shiva", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 303, name: "Ramuh", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 304, name: "Diabolos", type: "SummonerPact", mpCost: 15, minLevel: 1 },
    { id: 305, name: "Odin", type: "SummonerPact", mpCost: 0, minLevel: 75 },
    { id: 306, name: "Alexander", type: "SummonerPact", mpCost: 0, minLevel: 75 },
    { id: 307, name: "Cait Sith", type: "SummonerPact", mpCost: 5, minLevel: 1 },
    { id: 308, name: "Animus Augeo", type: "WhiteMagic", mpCost: 21, minLevel: 85 },
    { id: 309, name: "Animus Minuo", type: "WhiteMagic", mpCost: 21, minLevel: 85 },
    { id: 310, name: "Enlight", type: "WhiteMagic", mpCost: 24, minLevel: 85 },
    { id: 311, name: "Endark", type: "BlackMagic", mpCost: 24, minLevel: 85 },
    { id: 312, name: "Enfire II", type: "WhiteMagic", mpCost: 24, minLevel: 58 },
    { id: 313, name: "Enblizzard II", type: "WhiteMagic", mpCost: 24, minLevel: 56 },
    { id: 314, name: "Enaero II", type: "WhiteMagic", mpCost: 24, minLevel: 54 },
    { id: 315, name: "Enstone II", type: "WhiteMagic", mpCost: 24, minLevel: 52 },
    { id: 316, name: "Enthunder II", type: "WhiteMagic", mpCost: 24, minLevel: 50 },
    { id: 317, name: "Enwater II", type: "WhiteMagic", mpCost: 24, minLevel: 60 },
    { id: 318, name: "Monomi: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 25 },
    { id: 319, name: "Aisha: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 78 },
    { id: 320, name: "Katon: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 321, name: "Katon: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 322, name: "Katon: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 323, name: "Hyoton: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 324, name: "Hyoton: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 325, name: "Hyoton: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 326, name: "Huton: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 327, name: "Huton: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 328, name: "Huton: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 329, name: "Doton: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 330, name: "Doton: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 331, name: "Doton: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 332, name: "Raiton: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 333, name: "Raiton: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 334, name: "Raiton: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 335, name: "Suiton: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 15 },
    { id: 336, name: "Suiton: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 40 },
    { id: 337, name: "Suiton: San", type: "Ninjutsu", mpCost: 0, minLevel: 75 },
    { id: 338, name: "Utsusemi: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 12 },
    { id: 339, name: "Utsusemi: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 37 },
    { id: 340, name: "Utsusemi: San", type: "Ninjutsu", mpCost: 0, minLevel: 100 },
    { id: 341, name: "Jubaku: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 30 },
    { id: 342, name: "Jubaku: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 55 },
    { id: 343, name: "Jubaku: San", type: "Ninjutsu", mpCost: 0, minLevel: 0 },
    { id: 344, name: "Hojo: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 23 },
    { id: 345, name: "Hojo: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 48 },
    { id: 346, name: "Hojo: San", type: "Ninjutsu", mpCost: 0, minLevel: 73 },
    { id: 347, name: "Kurayami: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 19 },
    { id: 348, name: "Kurayami: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 44 },
    { id: 349, name: "Kurayami: San", type: "Ninjutsu", mpCost: 0, minLevel: 69 },
    { id: 350, name: "Dokumori: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 27 },
    { id: 351, name: "Dokumori: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 52 },
    { id: 352, name: "Dokumori: San", type: "Ninjutsu", mpCost: 0, minLevel: 0 },
    { id: 353, name: "Tonko: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 9 },
    { id: 354, name: "Tonko: Ni", type: "Ninjutsu", mpCost: 0, minLevel: 34 },
    { id: 355, name: "Siren", type: "SummonerPact", mpCost: 7, minLevel: 1 },
    { id: 356, name: "Paralyga", type: "WhiteMagic", mpCost: 12, minLevel: 61 },
    { id: 357, name: "Slowga", type: "WhiteMagic", mpCost: 30, minLevel: 61 },
    { id: 358, name: "Hastega", type: "WhiteMagic", mpCost: 80, minLevel: 61 },
    { id: 359, name: "Silencega", type: "WhiteMagic", mpCost: 32, minLevel: 61 },
    { id: 360, name: "Dispelga", type: "BlackMagic", mpCost: 200, minLevel: 99 },
    { id: 361, name: "Blindga", type: "BlackMagic", mpCost: 10, minLevel: 61 },
    { id: 362, name: "Bindga", type: "BlackMagic", mpCost: 16, minLevel: 61 },
    { id: 363, name: "Sleepga", type: "BlackMagic", mpCost: 38, minLevel: 31 },
    { id: 364, name: "Sleepga II", type: "BlackMagic", mpCost: 58, minLevel: 56 },
    { id: 365, name: "Breakga", type: "BlackMagic", mpCost: 78, minLevel: 95 },
    { id: 367, name: "Death", type: "BlackMagic", mpCost: 1, minLevel: 1200 },
    { id: 368, name: "Foe Requiem", type: "BardSong", mpCost: 0, minLevel: 7 },
    { id: 369, name: "Foe Requiem II", type: "BardSong", mpCost: 0, minLevel: 17 },
    { id: 370, name: "Foe Requiem III", type: "BardSong", mpCost: 0, minLevel: 37 },
    { id: 371, name: "Foe Requiem IV", type: "BardSong", mpCost: 0, minLevel: 47 },
    { id: 372, name: "Foe Requiem V", type: "BardSong", mpCost: 0, minLevel: 57 },
    { id: 373, name: "Foe Requiem VI", type: "BardSong", mpCost: 0, minLevel: 67 },
    { id: 374, name: "Foe Requiem VII", type: "BardSong", mpCost: 0, minLevel: 76 },
    { id: 376, name: "Horde Lullaby", type: "BardSong", mpCost: 0, minLevel: 27 },
    { id: 377, name: "Horde Lullaby II", type: "BardSong", mpCost: 0, minLevel: 92 },
    { id: 378, name: "Army's Paeon", type: "BardSong", mpCost: 0, minLevel: 5 },
    { id: 379, name: "Army's Paeon II", type: "BardSong", mpCost: 0, minLevel: 15 },
    { id: 380, name: "Army's Paeon III", type: "BardSong", mpCost: 0, minLevel: 35 },
    { id: 381, name: "Army's Paeon IV", type: "BardSong", mpCost: 0, minLevel: 45 },
    { id: 382, name: "Army's Paeon V", type: "BardSong", mpCost: 0, minLevel: 65 },
    { id: 383, name: "Army's Paeon VI", type: "BardSong", mpCost: 0, minLevel: 78 },
    { id: 386, name: "Mage's Ballad", type: "BardSong", mpCost: 0, minLevel: 25 },
    { id: 387, name: "Mage's Ballad II", type: "BardSong", mpCost: 0, minLevel: 55 },
    { id: 388, name: "Mage's Ballad III", type: "BardSong", mpCost: 0, minLevel: 85 },
    { id: 389, name: "Knight's Minne", type: "BardSong", mpCost: 0, minLevel: 1 },
    { id: 390, name: "Knight's Minne II", type: "BardSong", mpCost: 0, minLevel: 21 },
    { id: 391, name: "Knight's Minne III", type: "BardSong", mpCost: 0, minLevel: 41 },
    { id: 392, name: "Knight's Minne IV", type: "BardSong", mpCost: 0, minLevel: 61 },
    { id: 393, name: "Knight's Minne V", type: "BardSong", mpCost: 0, minLevel: 80 },
    { id: 394, name: "Valor Minuet", type: "BardSong", mpCost: 0, minLevel: 3 },
    { id: 395, name: "Valor Minuet II", type: "BardSong", mpCost: 0, minLevel: 23 },
    { id: 396, name: "Valor Minuet III", type: "BardSong", mpCost: 0, minLevel: 43 },
    { id: 397, name: "Valor Minuet IV", type: "BardSong", mpCost: 0, minLevel: 63 },
    { id: 398, name: "Valor Minuet V", type: "BardSong", mpCost: 0, minLevel: 87 },
    { id: 399, name: "Sword Madrigal", type: "BardSong", mpCost: 0, minLevel: 11 },
    { id: 400, name: "Blade Madrigal", type: "BardSong", mpCost: 0, minLevel: 51 },
    { id: 401, name: "Hunter's Prelude", type: "BardSong", mpCost: 0, minLevel: 31 },
    { id: 402, name: "Archer's Prelude", type: "BardSong", mpCost: 0, minLevel: 71 },
    { id: 403, name: "Sheepfoe Mambo", type: "BardSong", mpCost: 0, minLevel: 13 },
    { id: 404, name: "Dragonfoe Mambo", type: "BardSong", mpCost: 0, minLevel: 53 },
    { id: 405, name: "Fowl Aubade", type: "BardSong", mpCost: 0, minLevel: 33 },
    { id: 406, name: "Herb Pastoral", type: "BardSong", mpCost: 0, minLevel: 9 },
    { id: 407, name: "Chocobo Hum", type: "BardSong", mpCost: 0, minLevel: 52 },
    { id: 408, name: "Shining Fantasia", type: "BardSong", mpCost: 0, minLevel: 56 },
    { id: 409, name: "Scop's Operetta", type: "BardSong", mpCost: 0, minLevel: 19 },
    { id: 410, name: "Puppet's Operetta", type: "BardSong", mpCost: 0, minLevel: 69 },
    { id: 412, name: "Gold Capriccio", type: "BardSong", mpCost: 0, minLevel: 54 },
    { id: 414, name: "Warding Round", type: "BardSong", mpCost: 0, minLevel: 73 },
    { id: 415, name: "Goblin Gavotte", type: "BardSong", mpCost: 0, minLevel: 49 },
    { id: 416, name: "Cactuar Fugue", type: "BardSong", mpCost: 0, minLevel: 58 },
    { id: 419, name: "Advancing March", type: "BardSong", mpCost: 0, minLevel: 29 },
    { id: 420, name: "Victory March", type: "BardSong", mpCost: 0, minLevel: 60 },
    { id: 421, name: "Battlefield Elegy", type: "BardSong", mpCost: 0, minLevel: 39 },
    { id: 422, name: "Carnage Elegy", type: "BardSong", mpCost: 0, minLevel: 59 },
    { id: 424, name: "Sinewy Etude", type: "BardSong", mpCost: 0, minLevel: 34 },
    { id: 425, name: "Dextrous Etude", type: "BardSong", mpCost: 0, minLevel: 32 },
    { id: 426, name: "Vivacious Etude", type: "BardSong", mpCost: 0, minLevel: 30 },
    { id: 427, name: "Quick Etude", type: "BardSong", mpCost: 0, minLevel: 28 },
    { id: 428, name: "Learned Etude", type: "BardSong", mpCost: 0, minLevel: 26 },
    { id: 429, name: "Spirited Etude", type: "BardSong", mpCost: 0, minLevel: 24 },
    { id: 430, name: "Enchanting Etude", type: "BardSong", mpCost: 0, minLevel: 22 },
    { id: 431, name: "Herculean Etude", type: "BardSong", mpCost: 0, minLevel: 74 },
    { id: 432, name: "Uncanny Etude", type: "BardSong", mpCost: 0, minLevel: 72 },
    { id: 433, name: "Vital Etude", type: "BardSong", mpCost: 0, minLevel: 70 },
    { id: 434, name: "Swift Etude", type: "BardSong", mpCost: 0, minLevel: 68 },
    { id: 435, name: "Sage Etude", type: "BardSong", mpCost: 0, minLevel: 66 },
    { id: 436, name: "Logical Etude", type: "BardSong", mpCost: 0, minLevel: 64 },
    { id: 437, name: "Bewitching Etude", type: "BardSong", mpCost: 0, minLevel: 62 },
    { id: 438, name: "Fire Carol", type: "BardSong", mpCost: 0, minLevel: 44 },
    { id: 439, name: "Ice Carol", type: "BardSong", mpCost: 0, minLevel: 46 },
    { id: 440, name: "Wind Carol", type: "BardSong", mpCost: 0, minLevel: 42 },
    { id: 441, name: "Earth Carol", type: "BardSong", mpCost: 0, minLevel: 38 },
    { id: 442, name: "Lightning Carol", type: "BardSong", mpCost: 0, minLevel: 48 },
    { id: 443, name: "Water Carol", type: "BardSong", mpCost: 0, minLevel: 40 },
    { id: 444, name: "Light Carol", type: "BardSong", mpCost: 0, minLevel: 36 },
    { id: 445, name: "Dark Carol", type: "BardSong", mpCost: 0, minLevel: 50 },
    { id: 446, name: "Fire Carol II", type: "BardSong", mpCost: 0, minLevel: 90 },
    { id: 447, name: "Ice Carol II", type: "BardSong", mpCost: 0, minLevel: 93 },
    { id: 448, name: "Wind Carol II", type: "BardSong", mpCost: 0, minLevel: 87 },
    { id: 449, name: "Earth Carol II", type: "BardSong", mpCost: 0, minLevel: 81 },
    { id: 450, name: "Lightning Carol II", type: "BardSong", mpCost: 0, minLevel: 96 },
    { id: 451, name: "Water Carol II", type: "BardSong", mpCost: 0, minLevel: 84 },
    { id: 452, name: "Light Carol II", type: "BardSong", mpCost: 0, minLevel: 99 },
    { id: 453, name: "Dark Carol II", type: "BardSong", mpCost: 0, minLevel: 99 },
    { id: 454, name: "Fire Threnody", type: "BardSong", mpCost: 0, minLevel: 20 },
    { id: 455, name: "Ice Threnody", type: "BardSong", mpCost: 0, minLevel: 22 },
    { id: 456, name: "Wind Threnody", type: "BardSong", mpCost: 0, minLevel: 18 },
    { id: 457, name: "Earth Threnody", type: "BardSong", mpCost: 0, minLevel: 14 },
    { id: 458, name: "Ltng. Threnody", type: "BardSong", mpCost: 0, minLevel: 24 },
    { id: 459, name: "Water Threnody", type: "BardSong", mpCost: 0, minLevel: 16 },
    { id: 460, name: "Light Threnody", type: "BardSong", mpCost: 0, minLevel: 10 },
    { id: 461, name: "Dark Threnody", type: "BardSong", mpCost: 0, minLevel: 12 },
    { id: 462, name: "Magic Finale", type: "BardSong", mpCost: 0, minLevel: 33 },
    { id: 463, name: "Foe Lullaby", type: "BardSong", mpCost: 0, minLevel: 16 },
    { id: 464, name: "Goddess's Hymnus", type: "BardSong", mpCost: 0, minLevel: 71 },
    { id: 465, name: "Chocobo Mazurka", type: "BardSong", mpCost: 0, minLevel: 73 },
    { id: 466, name: "Maiden's Virelai", type: "BardSong", mpCost: 0, minLevel: 75 },
    { id: 467, name: "Raptor Mazurka", type: "BardSong", mpCost: 0, minLevel: 37 },
    { id: 468, name: "Foe Sirvente", type: "BardSong", mpCost: 0, minLevel: 75 },
    { id: 469, name: "Adventurer's Dirge", type: "BardSong", mpCost: 0, minLevel: 75 },
    { id: 470, name: "Sentinel's Scherzo", type: "BardSong", mpCost: 0, minLevel: 82 },
    { id: 471, name: "Foe Lullaby II", type: "BardSong", mpCost: 0, minLevel: 83 },
    { id: 472, name: "Pining Nocturne", type: "BardSong", mpCost: 0, minLevel: 95 },
    { id: 473, name: "Refresh II", type: "WhiteMagic", mpCost: 60, minLevel: 82 },
    { id: 474, name: "Cura II", type: "WhiteMagic", mpCost: 45, minLevel: 83 },
    { id: 475, name: "Cura III", type: "WhiteMagic", mpCost: 60, minLevel: 96 },
    { id: 476, name: "Crusade", type: "WhiteMagic", mpCost: 18, minLevel: 88 },
    { id: 477, name: "Regen IV", type: "WhiteMagic", mpCost: 82, minLevel: 79 },
    { id: 478, name: "Embrava", type: "WhiteMagic", mpCost: 1, minLevel: 5 },
    { id: 479, name: "Boost-STR", type: "WhiteMagic", mpCost: 36, minLevel: 93 },
    { id: 480, name: "Boost-DEX", type: "WhiteMagic", mpCost: 36, minLevel: 99 },
    { id: 481, name: "Boost-VIT", type: "WhiteMagic", mpCost: 36, minLevel: 81 },
    { id: 482, name: "Boost-AGI", type: "WhiteMagic", mpCost: 36, minLevel: 90 },
    { id: 483, name: "Boost-INT", type: "WhiteMagic", mpCost: 36, minLevel: 96 },
    { id: 484, name: "Boost-MND", type: "WhiteMagic", mpCost: 36, minLevel: 84 },
    { id: 485, name: "Boost-CHR", type: "WhiteMagic", mpCost: 36, minLevel: 87 },
    { id: 486, name: "Gain-STR", type: "WhiteMagic", mpCost: 36, minLevel: 93 },
    { id: 487, name: "Gain-DEX", type: "WhiteMagic", mpCost: 36, minLevel: 99 },
    { id: 488, name: "Gain-VIT", type: "WhiteMagic", mpCost: 36, minLevel: 81 },
    { id: 489, name: "Gain-AGI", type: "WhiteMagic", mpCost: 36, minLevel: 90 },
    { id: 490, name: "Gain-INT", type: "WhiteMagic", mpCost: 36, minLevel: 96 },
    { id: 491, name: "Gain-MND", type: "WhiteMagic", mpCost: 36, minLevel: 84 },
    { id: 492, name: "Gain-CHR", type: "WhiteMagic", mpCost: 36, minLevel: 87 },
    { id: 493, name: "Temper", type: "WhiteMagic", mpCost: 36, minLevel: 95 },
    { id: 494, name: "Arise", type: "WhiteMagic", mpCost: 300, minLevel: 99 },
    { id: 495, name: "Adloquium", type: "WhiteMagic", mpCost: 50, minLevel: 88 },
    { id: 496, name: "Firaja", type: "BlackMagic", mpCost: 358, minLevel: 90 },
    { id: 497, name: "Blizzaja", type: "BlackMagic", mpCost: 378, minLevel: 93 },
    { id: 498, name: "Aeroja", type: "BlackMagic", mpCost: 338, minLevel: 87 },
    { id: 499, name: "Stoneja", type: "BlackMagic", mpCost: 298, minLevel: 81 },
    { id: 500, name: "Thundaja", type: "BlackMagic", mpCost: 398, minLevel: 96 },
    { id: 501, name: "Waterja", type: "BlackMagic", mpCost: 318, minLevel: 84 },
    { id: 502, name: "Kaustra", type: "BlackMagic", mpCost: 1, minLevel: 5 },
    { id: 504, name: "Regen V", type: "WhiteMagic", mpCost: 100, minLevel: 99 },
    { id: 505, name: "Gekka: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 88 },
    { id: 506, name: "Yain: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 91 },
    { id: 507, name: "Myoshu: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 85 },
    { id: 508, name: "Yurin: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 83 },
    { id: 509, name: "Kakka: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 93 },
    { id: 510, name: "Migawari: Ichi", type: "Ninjutsu", mpCost: 0, minLevel: 88 },
    { id: 511, name: "Haste II", type: "WhiteMagic", mpCost: 80, minLevel: 96 },
    { id: 513, name: "Venom Shell", type: "BlueMagic", mpCost: 86, minLevel: 42 },
    { id: 515, name: "Maelstrom", type: "BlueMagic", mpCost: 162, minLevel: 61 },
    { id: 517, name: "Metallic Body", type: "BlueMagic", mpCost: 19, minLevel: 8 },
    { id: 519, name: "Screwdriver", type: "BlueMagic", mpCost: 21, minLevel: 26 },
    { id: 521, name: "MP Drainkiss", type: "BlueMagic", mpCost: 20, minLevel: 42 },
    { id: 522, name: "Death Ray", type: "BlueMagic", mpCost: 49, minLevel: 34 },
    { id: 524, name: "Sandspin", type: "BlueMagic", mpCost: 10, minLevel: 1 },
    { id: 527, name: "Smite of Rage", type: "BlueMagic", mpCost: 28, minLevel: 34 },
    { id: 529, name: "Bludgeon", type: "BlueMagic", mpCost: 16, minLevel: 18 },
    { id: 530, name: "Refueling", type: "BlueMagic", mpCost: 29, minLevel: 48 },
    { id: 531, name: "Ice Break", type: "BlueMagic", mpCost: 142, minLevel: 50 },
    { id: 532, name: "Blitzstrahl", type: "BlueMagic", mpCost: 70, minLevel: 44 },
    { id: 533, name: "Self-Destruct", type: "BlueMagic", mpCost: 100, minLevel: 50 },
    { id: 534, name: "Mysterious Light", type: "BlueMagic", mpCost: 73, minLevel: 40 },
    { id: 535, name: "Cold Wave", type: "BlueMagic", mpCost: 37, minLevel: 52 },
    { id: 536, name: "Poison Breath", type: "BlueMagic", mpCost: 22, minLevel: 22 },
    { id: 537, name: "Stinking Gas", type: "BlueMagic", mpCost: 37, minLevel: 44 },
    { id: 538, name: "Memento Mori", type: "BlueMagic", mpCost: 46, minLevel: 62 },
    { id: 539, name: "Terror Touch", type: "BlueMagic", mpCost: 62, minLevel: 40 },
    { id: 540, name: "Spinal Cleave", type: "BlueMagic", mpCost: 61, minLevel: 63 },
    { id: 541, name: "Blood Saber", type: "BlueMagic", mpCost: 25, minLevel: 48 },
    { id: 542, name: "Digest", type: "BlueMagic", mpCost: 20, minLevel: 36 },
    { id: 543, name: "Mandibular Bite", type: "BlueMagic", mpCost: 38, minLevel: 44 },
    { id: 544, name: "Cursed Sphere", type: "BlueMagic", mpCost: 36, minLevel: 18 },
    { id: 545, name: "Sickle Slash", type: "BlueMagic", mpCost: 41, minLevel: 48 },
    { id: 547, name: "Cocoon", type: "BlueMagic", mpCost: 10, minLevel: 8 },
    { id: 548, name: "Filamented Hold", type: "BlueMagic", mpCost: 38, minLevel: 52 },
    { id: 549, name: "Pollen", type: "BlueMagic", mpCost: 8, minLevel: 1 },
    { id: 551, name: "Power Attack", type: "BlueMagic", mpCost: 5, minLevel: 4 },
    { id: 554, name: "Death Scissors", type: "BlueMagic", mpCost: 51, minLevel: 60 },
    { id: 555, name: "Magnetite Cloud", type: "BlueMagic", mpCost: 86, minLevel: 46 },
    { id: 557, name: "Eyes On Me", type: "BlueMagic", mpCost: 112, minLevel: 61 },
    { id: 560, name: "Frenetic Rip", type: "BlueMagic", mpCost: 61, minLevel: 63 },
    { id: 561, name: "Frightful Roar", type: "BlueMagic", mpCost: 32, minLevel: 50 },
    { id: 563, name: "Hecatomb Wave", type: "BlueMagic", mpCost: 116, minLevel: 54 },
    { id: 564, name: "Body Slam", type: "BlueMagic", mpCost: 74, minLevel: 62 },
    { id: 565, name: "Radiant Breath", type: "BlueMagic", mpCost: 116, minLevel: 54 },
    { id: 567, name: "Helldive", type: "BlueMagic", mpCost: 16, minLevel: 16 },
    { id: 569, name: "Jet Stream", type: "BlueMagic", mpCost: 47, minLevel: 38 },
    { id: 570, name: "Blood Drain", type: "BlueMagic", mpCost: 10, minLevel: 20 },
    { id: 572, name: "Sound Blast", type: "BlueMagic", mpCost: 25, minLevel: 32 },
    { id: 573, name: "Feather Tickle", type: "BlueMagic", mpCost: 48, minLevel: 64 },
    { id: 574, name: "Feather Barrier", type: "BlueMagic", mpCost: 29, minLevel: 56 },
    { id: 575, name: "Jettatura", type: "BlueMagic", mpCost: 37, minLevel: 48 },
    { id: 576, name: "Yawn", type: "BlueMagic", mpCost: 55, minLevel: 64 },
    { id: 577, name: "Foot Kick", type: "BlueMagic", mpCost: 5, minLevel: 1 },
    { id: 578, name: "Wild Carrot", type: "BlueMagic", mpCost: 37, minLevel: 30 },
    { id: 579, name: "Voracious Trunk", type: "BlueMagic", mpCost: 72, minLevel: 64 },
    { id: 581, name: "Healing Breeze", type: "BlueMagic", mpCost: 55, minLevel: 16 },
    { id: 582, name: "Chaotic Eye", type: "BlueMagic", mpCost: 13, minLevel: 32 },
    { id: 584, name: "Sheep Song", type: "BlueMagic", mpCost: 22, minLevel: 16 },
    { id: 585, name: "Ram Charge", type: "BlueMagic", mpCost: 79, minLevel: 73 },
    { id: 587, name: "Claw Cyclone", type: "BlueMagic", mpCost: 24, minLevel: 20 },
    { id: 588, name: "Lowing", type: "BlueMagic", mpCost: 66, minLevel: 71 },
    { id: 589, name: "Dimensional Death", type: "BlueMagic", mpCost: 48, minLevel: 60 },
    { id: 591, name: "Heat Breath", type: "BlueMagic", mpCost: 169, minLevel: 71 },
    { id: 592, name: "Blank Gaze", type: "BlueMagic", mpCost: 25, minLevel: 38 },
    { id: 593, name: "Magic Fruit", type: "BlueMagic", mpCost: 72, minLevel: 58 },
    { id: 594, name: "Uppercut", type: "BlueMagic", mpCost: 31, minLevel: 38 },
    { id: 595, name: "1000 Needles", type: "BlueMagic", mpCost: 350, minLevel: 62 },
    { id: 596, name: "Pinecone Bomb", type: "BlueMagic", mpCost: 48, minLevel: 36 },
    { id: 597, name: "Sprout Smack", type: "BlueMagic", mpCost: 6, minLevel: 4 },
    { id: 598, name: "Soporific", type: "BlueMagic", mpCost: 38, minLevel: 24 },
    { id: 599, name: "Queasyshroom", type: "BlueMagic", mpCost: 20, minLevel: 8 },
    { id: 603, name: "Wild Oats", type: "BlueMagic", mpCost: 9, minLevel: 4 },
    { id: 604, name: "Bad Breath", type: "BlueMagic", mpCost: 212, minLevel: 61 },
    { id: 605, name: "Geist Wall", type: "BlueMagic", mpCost: 35, minLevel: 46 },
    { id: 606, name: "Awful Eye", type: "BlueMagic", mpCost: 32, minLevel: 46 },
    { id: 608, name: "Frost Breath", type: "BlueMagic", mpCost: 136, minLevel: 66 },
    { id: 610, name: "Infrasonics", type: "BlueMagic", mpCost: 42, minLevel: 65 },
    { id: 611, name: "Disseverment", type: "BlueMagic", mpCost: 74, minLevel: 72 },
    { id: 612, name: "Actinic Burst", type: "BlueMagic", mpCost: 24, minLevel: 74 },
    { id: 613, name: "Reactor Cool", type: "BlueMagic", mpCost: 28, minLevel: 74 },
    { id: 614, name: "Saline Coat", type: "BlueMagic", mpCost: 66, minLevel: 72 },
    { id: 615, name: "Plasma Charge", type: "BlueMagic", mpCost: 24, minLevel: 75 },
    { id: 616, name: "Temporal Shift", type: "BlueMagic", mpCost: 48, minLevel: 73 },
    { id: 617, name: "Vertical Cleave", type: "BlueMagic", mpCost: 86, minLevel: 75 },
    { id: 618, name: "Blastbomb", type: "BlueMagic", mpCost: 36, minLevel: 18 },
    { id: 620, name: "Battle Dance", type: "BlueMagic", mpCost: 12, minLevel: 12 },
    { id: 621, name: "Sandspray", type: "BlueMagic", mpCost: 43, minLevel: 66 },
    { id: 622, name: "Grand Slam", type: "BlueMagic", mpCost: 24, minLevel: 30 },
    { id: 623, name: "Head Butt", type: "BlueMagic", mpCost: 12, minLevel: 12 },
    { id: 626, name: "Bomb Toss", type: "BlueMagic", mpCost: 42, minLevel: 28 },
    { id: 628, name: "Frypan", type: "BlueMagic", mpCost: 65, minLevel: 63 },
    { id: 629, name: "Flying Hip Press", type: "BlueMagic", mpCost: 125, minLevel: 58 },
    { id: 631, name: "Hydro Shot", type: "BlueMagic", mpCost: 55, minLevel: 63 },
    { id: 632, name: "Diamondhide", type: "BlueMagic", mpCost: 99, minLevel: 67 },
    { id: 633, name: "Enervation", type: "BlueMagic", mpCost: 48, minLevel: 67 },
    { id: 634, name: "Light of Penance", type: "BlueMagic", mpCost: 53, minLevel: 58 },
    { id: 636, name: "Warm-Up", type: "BlueMagic", mpCost: 59, minLevel: 68 },
    { id: 637, name: "Firespit", type: "BlueMagic", mpCost: 121, minLevel: 68 },
    { id: 638, name: "Feather Storm", type: "BlueMagic", mpCost: 12, minLevel: 12 },
    { id: 640, name: "Tail Slap", type: "BlueMagic", mpCost: 77, minLevel: 69 },
    { id: 641, name: "Hysteric Barrage", type: "BlueMagic", mpCost: 61, minLevel: 69 },
    { id: 642, name: "Amplification", type: "BlueMagic", mpCost: 48, minLevel: 70 },
    { id: 643, name: "Cannonball", type: "BlueMagic", mpCost: 66, minLevel: 70 },
    { id: 644, name: "Mind Blast", type: "BlueMagic", mpCost: 82, minLevel: 73 },
    { id: 645, name: "Exuviation", type: "BlueMagic", mpCost: 40, minLevel: 75 },
    { id: 646, name: "Magic Hammer", type: "BlueMagic", mpCost: 40, minLevel: 74 },
    { id: 647, name: "Zephyr Mantle", type: "BlueMagic", mpCost: 31, minLevel: 65 },
    { id: 648, name: "Regurgitation", type: "BlueMagic", mpCost: 69, minLevel: 69 },
    { id: 650, name: "Seedspray", type: "BlueMagic", mpCost: 61, minLevel: 61 },
    { id: 651, name: "Corrosive Ooze", type: "BlueMagic", mpCost: 55, minLevel: 66 },
    { id: 652, name: "Spiral Spin", type: "BlueMagic", mpCost: 39, minLevel: 60 },
    { id: 653, name: "Asuran Claws", type: "BlueMagic", mpCost: 81, minLevel: 70 },
    { id: 654, name: "Sub-zero Smash", type: "BlueMagic", mpCost: 44, minLevel: 72 },
    { id: 655, name: "Triumphant Roar", type: "BlueMagic", mpCost: 24, minLevel: 71 },
    { id: 656, name: "Acrid Stream", type: "BlueMagic", mpCost: 89, minLevel: 77 },
    { id: 657, name: "Blazing Bound", type: "BlueMagic", mpCost: 113, minLevel: 80 },
    { id: 658, name: "Plenilune Embrace", type: "BlueMagic", mpCost: 106, minLevel: 76 },
    { id: 659, name: "Demoralizing Roar", type: "BlueMagic", mpCost: 46, minLevel: 80 },
    { id: 660, name: "Cimicine Discharge", type: "BlueMagic", mpCost: 32, minLevel: 78 },
    { id: 661, name: "Animating Wail", type: "BlueMagic", mpCost: 53, minLevel: 79 },
    { id: 662, name: "Battery Charge", type: "BlueMagic", mpCost: 50, minLevel: 79 },
    { id: 663, name: "Leafstorm", type: "BlueMagic", mpCost: 132, minLevel: 77 },
    { id: 664, name: "Regeneration", type: "BlueMagic", mpCost: 36, minLevel: 78 },
    { id: 665, name: "Final Sting", type: "BlueMagic", mpCost: 88, minLevel: 81 },
    { id: 666, name: "Goblin Rush", type: "BlueMagic", mpCost: 76, minLevel: 81 },
    { id: 667, name: "Vanity Dive", type: "BlueMagic", mpCost: 58, minLevel: 82 },
    { id: 668, name: "Magic Barrier", type: "BlueMagic", mpCost: 29, minLevel: 82 },
    { id: 669, name: "Whirl of Rage", type: "BlueMagic", mpCost: 73, minLevel: 83 },
    { id: 670, name: "Benthic Typhoon", type: "BlueMagic", mpCost: 43, minLevel: 83 },
    { id: 671, name: "Auroral Drape", type: "BlueMagic", mpCost: 51, minLevel: 84 },
    { id: 672, name: "Osmosis", type: "BlueMagic", mpCost: 47, minLevel: 84 },
    { id: 673, name: "Quad. Continuum", type: "BlueMagic", mpCost: 91, minLevel: 85 },
    { id: 674, name: "Fantod", type: "BlueMagic", mpCost: 12, minLevel: 85 },
    { id: 675, name: "Thermal Pulse", type: "BlueMagic", mpCost: 151, minLevel: 86 },
    { id: 677, name: "Empty Thrash", type: "BlueMagic", mpCost: 33, minLevel: 87 },
    { id: 678, name: "Dream Flower", type: "BlueMagic", mpCost: 68, minLevel: 87 },
    { id: 679, name: "Occultation", type: "BlueMagic", mpCost: 138, minLevel: 88 },
    { id: 680, name: "Charged Whisker", type: "BlueMagic", mpCost: 183, minLevel: 88 },
    { id: 681, name: "Winds of Promy.", type: "BlueMagic", mpCost: 36, minLevel: 89 },
    { id: 682, name: "Delta Thrust", type: "BlueMagic", mpCost: 28, minLevel: 89 },
    { id: 683, name: "Evryone. Grudge", type: "BlueMagic", mpCost: 185, minLevel: 90 },
    { id: 684, name: "Reaving Wind", type: "BlueMagic", mpCost: 84, minLevel: 90 },
    { id: 685, name: "Barrier Tusk", type: "BlueMagic", mpCost: 41, minLevel: 91 },
    { id: 686, name: "Mortal Ray", type: "BlueMagic", mpCost: 267, minLevel: 91 },
    { id: 687, name: "Water Bomb", type: "BlueMagic", mpCost: 67, minLevel: 92 },
    { id: 688, name: "Heavy Strike", type: "BlueMagic", mpCost: 32, minLevel: 92 },
    { id: 689, name: "Dark Orb", type: "BlueMagic", mpCost: 124, minLevel: 93 },
    { id: 690, name: "White Wind", type: "BlueMagic", mpCost: 145, minLevel: 94 },
    { id: 692, name: "Sudden Lunge", type: "BlueMagic", mpCost: 18, minLevel: 95 },
    { id: 693, name: "Quadrastrike", type: "BlueMagic", mpCost: 98, minLevel: 96 },
    { id: 694, name: "Vapor Spray", type: "BlueMagic", mpCost: 172, minLevel: 96 },
    { id: 695, name: "Thunder Breath", type: "BlueMagic", mpCost: 193, minLevel: 97 },
    { id: 696, name: "O. Counterstance", type: "BlueMagic", mpCost: 18, minLevel: 98 },
    { id: 697, name: "Amorphic Spikes", type: "BlueMagic", mpCost: 79, minLevel: 98 },
    { id: 698, name: "Wind Breath", type: "BlueMagic", mpCost: 26, minLevel: 99 },
    { id: 699, name: "Barbed Crescent", type: "BlueMagic", mpCost: 52, minLevel: 99 },
    { id: 700, name: "Nat. Meditation", type: "BlueMagic", mpCost: 38, minLevel: 99 },
    { id: 701, name: "Tem. Upheaval", type: "BlueMagic", mpCost: 133, minLevel: 99 },
    { id: 702, name: "Rending Deluge", type: "BlueMagic", mpCost: 118, minLevel: 99 },
    { id: 703, name: "Embalming Earth", type: "BlueMagic", mpCost: 57, minLevel: 99 },
    { id: 704, name: "Paralyzing Triad", type: "BlueMagic", mpCost: 33, minLevel: 99 },
    { id: 705, name: "Foul Waters", type: "BlueMagic", mpCost: 76, minLevel: 99 },
    { id: 706, name: "Glutinous Dart", type: "BlueMagic", mpCost: 16, minLevel: 99 },
    { id: 707, name: "Retinal Glare", type: "BlueMagic", mpCost: 26, minLevel: 99 },
    { id: 708, name: "Subduction", type: "BlueMagic", mpCost: 27, minLevel: 99 },
    { id: 709, name: "Thrashing Assault", type: "BlueMagic", mpCost: 119, minLevel: 99 },
    { id: 710, name: "Erratic Flutter", type: "BlueMagic", mpCost: 92, minLevel: 99 },
    { id: 711, name: "Restoral", type: "BlueMagic", mpCost: 127, minLevel: 99 },
    { id: 712, name: "Rail Cannon", type: "BlueMagic", mpCost: 200, minLevel: 99 },
    { id: 713, name: "Diffusion Ray", type: "BlueMagic", mpCost: 238, minLevel: 99 },
    { id: 714, name: "Sinker Drill", type: "BlueMagic", mpCost: 91, minLevel: 99 },
    { id: 715, name: "Molting Plumage", type: "BlueMagic", mpCost: 146, minLevel: 99 },
    { id: 716, name: "Nectarous Deluge", type: "BlueMagic", mpCost: 97, minLevel: 99 },
    { id: 717, name: "Sweeping Gouge", type: "BlueMagic", mpCost: 29, minLevel: 99 },
    { id: 718, name: "Atra. Libations", type: "BlueMagic", mpCost: 164, minLevel: 99 },
    { id: 719, name: "Searing Tempest", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 720, name: "Spectral Floe", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 721, name: "Anvil Lightning", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 722, name: "Entomb", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 723, name: "Saurian Slide", type: "BlueMagic", mpCost: 109, minLevel: 99 },
    { id: 724, name: "Palling Salvo", type: "BlueMagic", mpCost: 175, minLevel: 99 },
    { id: 725, name: "Blinding Fulgor", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 726, name: "Scouring Spate", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 727, name: "Silent Storm", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 728, name: "Tenebral Crush", type: "BlueMagic", mpCost: 116, minLevel: 99 },
    { id: 736, name: "Thunderbolt", type: "BlueMagic", mpCost: 138, minLevel: 95 },
    { id: 737, name: "Harden Shell", type: "BlueMagic", mpCost: 20, minLevel: 95 },
    { id: 738, name: "Absolute Terror", type: "BlueMagic", mpCost: 29, minLevel: 96 },
    { id: 739, name: "Gates of Hades", type: "BlueMagic", mpCost: 156, minLevel: 97 },
    { id: 740, name: "Tourbillion", type: "BlueMagic", mpCost: 108, minLevel: 97 },
    { id: 741, name: "Pyric Bulwark", type: "BlueMagic", mpCost: 50, minLevel: 98 },
    { id: 742, name: "Bilgestorm", type: "BlueMagic", mpCost: 122, minLevel: 99 },
    { id: 743, name: "Bloodrake", type: "BlueMagic", mpCost: 99, minLevel: 99 },
    { id: 744, name: "Droning Whirlwind", type: "BlueMagic", mpCost: 224, minLevel: 99 },
    { id: 745, name: "Carcharian Verve", type: "BlueMagic", mpCost: 65, minLevel: 99 },
    { id: 746, name: "Blistering Roar", type: "BlueMagic", mpCost: 43, minLevel: 99 },
    { id: 747, name: "Uproot", type: "BlueMagic", mpCost: 88, minLevel: 99 },
    { id: 748, name: "Crashing Thunder", type: "BlueMagic", mpCost: 172, minLevel: 99 },
    { id: 749, name: "Polar Roar", type: "BlueMagic", mpCost: 126, minLevel: 99 },
    { id: 750, name: "Mighty Guard", type: "BlueMagic", mpCost: 299, minLevel: 99 },
    { id: 751, name: "Cruel Joke", type: "BlueMagic", mpCost: 187, minLevel: 99 },
    { id: 752, name: "Cesspool", type: "BlueMagic", mpCost: 166, minLevel: 99 },
    { id: 753, name: "Tearing Gust", type: "BlueMagic", mpCost: 202, minLevel: 99 },
    { id: 768, name: "Indi-Regen", type: "Geomancy", mpCost: 37, minLevel: 15 },
    { id: 769, name: "Indi-Poison", type: "Geomancy", mpCost: 12, minLevel: 1 },
    { id: 770, name: "Indi-Refresh", type: "Geomancy", mpCost: 63, minLevel: 30 },
    { id: 771, name: "Indi-Haste", type: "Geomancy", mpCost: 100, minLevel: 93 },
    { id: 772, name: "Indi-STR", type: "Geomancy", mpCost: 63, minLevel: 48 },
    { id: 773, name: "Indi-DEX", type: "Geomancy", mpCost: 63, minLevel: 45 },
    { id: 774, name: "Indi-VIT", type: "Geomancy", mpCost: 63, minLevel: 42 },
    { id: 775, name: "Indi-AGI", type: "Geomancy", mpCost: 63, minLevel: 39 },
    { id: 776, name: "Indi-INT", type: "Geomancy", mpCost: 63, minLevel: 36 },
    { id: 777, name: "Indi-MND", type: "Geomancy", mpCost: 63, minLevel: 33 },
    { id: 778, name: "Indi-CHR", type: "Geomancy", mpCost: 63, minLevel: 30 },
    { id: 779, name: "Indi-Fury", type: "Geomancy", mpCost: 70, minLevel: 34 },
    { id: 780, name: "Indi-Barrier", type: "Geomancy", mpCost: 59, minLevel: 28 },
    { id: 781, name: "Indi-Acumen", type: "Geomancy", mpCost: 91, minLevel: 46 },
    { id: 782, name: "Indi-Fend", type: "Geomancy", mpCost: 80, minLevel: 40 },
    { id: 783, name: "Indi-Precision", type: "Geomancy", mpCost: 25, minLevel: 10 },
    { id: 784, name: "Indi-Voidance", type: "Geomancy", mpCost: 17, minLevel: 4 },
    { id: 785, name: "Indi-Focus", type: "Geomancy", mpCost: 49, minLevel: 22 },
    { id: 786, name: "Indi-Attunement", type: "Geomancy", mpCost: 38, minLevel: 16 },
    { id: 787, name: "Indi-Wilt", type: "Geomancy", mpCost: 161, minLevel: 82 },
    { id: 788, name: "Indi-Frailty", type: "Geomancy", mpCost: 147, minLevel: 76 },
    { id: 789, name: "Indi-Fade", type: "Geomancy", mpCost: 186, minLevel: 94 },
    { id: 790, name: "Indi-Malaise", type: "Geomancy", mpCost: 174, minLevel: 88 },
    { id: 791, name: "Indi-Slip", type: "Geomancy", mpCost: 112, minLevel: 58 },
    { id: 792, name: "Indi-Torpor", type: "Geomancy", mpCost: 101, minLevel: 52 },
    { id: 793, name: "Indi-Vex", type: "Geomancy", mpCost: 136, minLevel: 70 },
    { id: 794, name: "Indi-Languor", type: "Geomancy", mpCost: 124, minLevel: 64 },
    { id: 795, name: "Indi-Slow", type: "Geomancy", mpCost: 94, minLevel: 48 },
    { id: 796, name: "Indi-Paralysis", type: "Geomancy", mpCost: 107, minLevel: 68 },
    { id: 797, name: "Indi-Gravity", type: "Geomancy", mpCost: 174, minLevel: 88 },
    { id: 798, name: "Geo-Regen", type: "Geomancy", mpCost: 74, minLevel: 19 },
    { id: 799, name: "Geo-Poison", type: "Geomancy", mpCost: 25, minLevel: 5 },
    { id: 800, name: "Geo-Refresh", type: "Geomancy", mpCost: 126, minLevel: 34 },
    { id: 801, name: "Geo-Haste", type: "Geomancy", mpCost: 200, minLevel: 97 },
    { id: 802, name: "Geo-STR", type: "Geomancy", mpCost: 126, minLevel: 52 },
    { id: 803, name: "Geo-DEX", type: "Geomancy", mpCost: 126, minLevel: 49 },
    { id: 804, name: "Geo-VIT", type: "Geomancy", mpCost: 126, minLevel: 46 },
    { id: 805, name: "Geo-AGI", type: "Geomancy", mpCost: 126, minLevel: 43 },
    { id: 806, name: "Geo-INT", type: "Geomancy", mpCost: 126, minLevel: 40 },
    { id: 807, name: "Geo-MND", type: "Geomancy", mpCost: 126, minLevel: 37 },
    { id: 808, name: "Geo-CHR", type: "Geomancy", mpCost: 126, minLevel: 34 },
    { id: 809, name: "Geo-Fury", type: "Geomancy", mpCost: 140, minLevel: 38 },
    { id: 810, name: "Geo-Barrier", type: "Geomancy", mpCost: 119, minLevel: 32 },
    { id: 811, name: "Geo-Acumen", type: "Geomancy", mpCost: 182, minLevel: 50 },
    { id: 812, name: "Geo-Fend", type: "Geomancy", mpCost: 161, minLevel: 44 },
    { id: 813, name: "Geo-Precision", type: "Geomancy", mpCost: 50, minLevel: 14 },
    { id: 814, name: "Geo-Voidance", type: "Geomancy", mpCost: 35, minLevel: 8 },
    { id: 815, name: "Geo-Focus", type: "Geomancy", mpCost: 98, minLevel: 26 },
    { id: 816, name: "Geo-Attunement", type: "Geomancy", mpCost: 77, minLevel: 20 },
    { id: 817, name: "Geo-Wilt", type: "Geomancy", mpCost: 322, minLevel: 86 },
    { id: 818, name: "Geo-Frailty", type: "Geomancy", mpCost: 294, minLevel: 80 },
    { id: 819, name: "Geo-Fade", type: "Geomancy", mpCost: 372, minLevel: 98 },
    { id: 820, name: "Geo-Malaise", type: "Geomancy", mpCost: 348, minLevel: 92 },
    { id: 821, name: "Geo-Slip", type: "Geomancy", mpCost: 225, minLevel: 62 },
    { id: 822, name: "Geo-Torpor", type: "Geomancy", mpCost: 203, minLevel: 56 },
    { id: 823, name: "Geo-Vex", type: "Geomancy", mpCost: 273, minLevel: 74 },
    { id: 824, name: "Geo-Languor", type: "Geomancy", mpCost: 249, minLevel: 68 },
    { id: 825, name: "Geo-Slow", type: "Geomancy", mpCost: 189, minLevel: 52 },
    { id: 826, name: "Geo-Paralysis", type: "Geomancy", mpCost: 215, minLevel: 72 },
    { id: 827, name: "Geo-Gravity", type: "Geomancy", mpCost: 348, minLevel: 92 },
    { id: 828, name: "Fira", type: "BlackMagic", mpCost: 93, minLevel: 40 },
    { id: 829, name: "Fira II", type: "BlackMagic", mpCost: 206, minLevel: 85 },
    { id: 830, name: "Blizzara", type: "BlackMagic", mpCost: 108, minLevel: 45 },
    { id: 831, name: "Blizzara II", type: "BlackMagic", mpCost: 229, minLevel: 90 },
    { id: 832, name: "Aera", type: "BlackMagic", mpCost: 79, minLevel: 35 },
    { id: 833, name: "Aera II", type: "BlackMagic", mpCost: 184, minLevel: 80 },
    { id: 834, name: "Stonera", type: "BlackMagic", mpCost: 54, minLevel: 25 },
    { id: 835, name: "Stonera II", type: "BlackMagic", mpCost: 143, minLevel: 70 },
    { id: 836, name: "Thundara", type: "BlackMagic", mpCost: 123, minLevel: 50 },
    { id: 837, name: "Thundara II", type: "BlackMagic", mpCost: 253, minLevel: 95 },
    { id: 838, name: "Watera", type: "BlackMagic", mpCost: 66, minLevel: 30 },
    { id: 839, name: "Watera II", type: "BlackMagic", mpCost: 163, minLevel: 75 },
    { id: 840, name: "Foil", type: "WhiteMagic", mpCost: 48, minLevel: 58 },
    { id: 841, name: "Distract", type: "BlackMagic", mpCost: 32, minLevel: 35 },
    { id: 842, name: "Distract II", type: "BlackMagic", mpCost: 58, minLevel: 85 },
    { id: 843, name: "Frazzle", type: "BlackMagic", mpCost: 38, minLevel: 42 },
    { id: 844, name: "Frazzle II", type: "BlackMagic", mpCost: 64, minLevel: 92 },
    { id: 845, name: "Flurry", type: "WhiteMagic", mpCost: 40, minLevel: 48 },
    { id: 846, name: "Flurry II", type: "WhiteMagic", mpCost: 80, minLevel: 96 },
    { id: 847, name: "Atomos", type: "SummonerPact", mpCost: 50, minLevel: 75 },
    { id: 848, name: "Reraise IV", type: "WhiteMagic", mpCost: 150, minLevel: 100 },
    { id: 849, name: "Fire VI", type: "BlackMagic", mpCost: 339, minLevel: 100 },
    { id: 850, name: "Blizzard VI", type: "BlackMagic", mpCost: 386, minLevel: 100 },
    { id: 851, name: "Aero VI", type: "BlackMagic", mpCost: 299, minLevel: 100 },
    { id: 852, name: "Stone VI", type: "BlackMagic", mpCost: 237, minLevel: 100 },
    { id: 853, name: "Thunder VI", type: "BlackMagic", mpCost: 437, minLevel: 100 },
    { id: 854, name: "Water VI", type: "BlackMagic", mpCost: 266, minLevel: 100 },
    { id: 855, name: "Enlight II", type: "WhiteMagic", mpCost: 36, minLevel: 100 },
    { id: 856, name: "Endark II", type: "BlackMagic", mpCost: 36, minLevel: 100 },
    { id: 857, name: "Sandstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 858, name: "Rainstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 859, name: "Windstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 860, name: "Firestorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 861, name: "Hailstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 862, name: "Thunderstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 863, name: "Voidstorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 864, name: "Aurorastorm II", type: "WhiteMagic", mpCost: 60, minLevel: 100 },
    { id: 865, name: "Fira III", type: "BlackMagic", mpCost: 390, minLevel: 1200 },
    { id: 866, name: "Blizzara III", type: "BlackMagic", mpCost: 432, minLevel: 1200 },
    { id: 867, name: "Aera III", type: "BlackMagic", mpCost: 350, minLevel: 1200 },
    { id: 868, name: "Stonera III", type: "BlackMagic", mpCost: 276, minLevel: 1200 },
    { id: 869, name: "Thundara III", type: "BlackMagic", mpCost: 476, minLevel: 1200 },
    { id: 870, name: "Watera III", type: "BlackMagic", mpCost: 312, minLevel: 1200 },
    { id: 871, name: "Fire Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 872, name: "Ice Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 873, name: "Wind Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 874, name: "Earth Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 875, name: "Ltng. Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 876, name: "Water Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 877, name: "Light Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 878, name: "Dark Threnody II", type: "BardSong", mpCost: 0, minLevel: 100 },
    { id: 879, name: "Inundation", type: "WhiteMagic", mpCost: 48, minLevel: 64 },
    { id: 880, name: "Drain III", type: "BlackMagic", mpCost: 53, minLevel: 550 },
    { id: 881, name: "Aspir III", type: "BlackMagic", mpCost: 2, minLevel: 550 },
    { id: 882, name: "Distract III", type: "BlackMagic", mpCost: 84, minLevel: 550 },
    { id: 883, name: "Frazzle III", type: "BlackMagic", mpCost: 90, minLevel: 550 },
    { id: 884, name: "Addle II", type: "WhiteMagic", mpCost: 63, minLevel: 550 },
    { id: 885, name: "Geohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 886, name: "Hydrohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 887, name: "Anemohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 888, name: "Pyrohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 889, name: "Cryohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 890, name: "Ionohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 891, name: "Noctohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 892, name: "Luminohelix II", type: "BlackMagic", mpCost: 78, minLevel: 1200 },
    { id: 893, name: "Full Cure", type: "WhiteMagic", mpCost: 1, minLevel: 1200 },
    { id: 894, name: "Refresh III", type: "WhiteMagic", mpCost: 80, minLevel: 1200 },
    { id: 895, name: "Temper II", type: "WhiteMagic", mpCost: 72, minLevel: 1200 },
    { id: 896, name: "Shantotto", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 897, name: "Naji", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 898, name: "Kupipi", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 899, name: "Excenmille", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 900, name: "Ayame", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 901, name: "Nanaa Mihgo", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 902, name: "Curilla", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 903, name: "Volker", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 904, name: "Ajido-Marujido", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 905, name: "Trion", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 906, name: "Zeid", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 907, name: "Lion", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 908, name: "Tenzen", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 909, name: "Mihli Aliapoh", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 910, name: "Valaineral", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 911, name: "Joachim", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 912, name: "Naja Salaheem", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 913, name: "Prishe", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 914, name: "Ulmia", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 915, name: "Shikaree Z", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 916, name: "Cherukiki", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 917, name: "Iron Eater", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 918, name: "Gessho", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 919, name: "Gadalar", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 920, name: "Rainemard", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 921, name: "Ingrid", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 922, name: "Lehko Habhoka", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 923, name: "Nashmeira", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 924, name: "Zazarg", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 925, name: "Ovjang", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 926, name: "Mnejing", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 927, name: "Sakura", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 928, name: "Luzaf", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 929, name: "Najelith", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 930, name: "Aldo", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 931, name: "Moogle", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 932, name: "Fablinix", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 933, name: "Maat", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 934, name: "D. Shantotto", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 935, name: "Star Sibyl", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 936, name: "Karaha-Baruha", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 937, name: "Cid", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 938, name: "Gilgamesh", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 939, name: "Areuhat", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 940, name: "Semih Lafihna", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 941, name: "Elivira", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 942, name: "Noillurie", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 943, name: "Lhu Mhakaracca", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 944, name: "Ferreous Coffin", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 945, name: "Lilisette", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 946, name: "Mumor", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 947, name: "Uka Totlihn", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 948, name: "Klara", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 949, name: "Romaa Mihgo", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 950, name: "Kuyin Hathdenna", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 951, name: "Rahal", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 952, name: "Koru-Moru", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 958, name: "Babban", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 959, name: "Abenzio", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 960, name: "Rughadjeen", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 961, name: "Kukki-Chebukki", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 962, name: "Margret", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 963, name: "Chacharoon", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 964, name: "Lhe Lhangavo", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 965, name: "Arciela", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 966, name: "Mayakov", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 967, name: "Qultada", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 968, name: "Adelheid", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 969, name: "Amchuchu", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 970, name: "Brygid", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 971, name: "Mildaurion", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 972, name: "Halver", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 973, name: "Rongelouts", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 974, name: "Leonoyne", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 975, name: "Maximilian", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 976, name: "Kayeel-Payeel", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 977, name: "Robel-Akbel", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 978, name: "Kupofried", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 979, name: "Selh'teus", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 982, name: "Abquhbah", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 983, name: "Balamor", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 984, name: "August", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 985, name: "Rosulatia", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 986, name: "Teodor", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 987, name: "Ullegore", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 988, name: "Makki-Chebukki", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 989, name: "King of Hearts", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 990, name: "Morimar", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 991, name: "Darrcuiln", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 992, name: "AAHM", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 993, name: "AAEV", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 994, name: "AAMR", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 995, name: "AATT", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 996, name: "AAGK", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 997, name: "Iroha", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 998, name: "Ygnas", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 999, name: "Monberaux", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1004, name: "Excenmille [S]", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1009, name: "Lion II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1010, name: "Zeid II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1011, name: "Prishe II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1012, name: "Nashmeira II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1013, name: "Lilisette II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1014, name: "Tenzen II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1015, name: "Mumor II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1016, name: "Ingrid II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1017, name: "Arciela II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1018, name: "Iroha II", type: "Trust", mpCost: 0, minLevel: 1 },
    { id: 1019, name: "Shantotto II", type: "Trust", mpCost: 0, minLevel: 1 },
]

const SPELL_BY_ID = new Map<number, SpellCatalogEntry>(SPELLS.map(s => [s.id, s]))

export function lookupSpell(id: number): SpellCatalogEntry {
    const found = SPELL_BY_ID.get(id)
    if (found) return found
    return { id, name: `Spell #${id}`, type: 'WhiteMagic', mpCost: 0, minLevel: 0 }
}

// Spell types learned from a "Scroll of {name}" item. Blue Magic (learned by
// being hit by a monster move), Summoner pacts (avatar fights/items), and
// Trusts (cipher/quest items) have no scroll and are intentionally excluded.
const SCROLL_LEARNABLE = new Set<SpellType>([
    'WhiteMagic', 'BlackMagic', 'Ninjutsu', 'BardSong', 'Geomancy',
])

export const isScrollLearnable = (type: SpellType): boolean =>
    SCROLL_LEARNABLE.has(type)

// Deep link to BG-Wiki. Scroll-learnable spells point at the scroll item
// ("Scroll of {name}") so players can see how to obtain it; scroll-less spells
// point at the spell's own page. Uses the MediaWiki search URL (not a guessed
// /ffxi/<slug>) so it never hard-404s — matches keyItemWikiUrl in key-items.ts.
export function spellWikiUrl(spell: SpellCatalogEntry): string {
    const q = isScrollLearnable(spell.type)
        ? `Scroll of ${spell.name}`
        : spell.name
    return `https://www.bg-wiki.com/index.php?search=${encodeURIComponent(q)}`
}

export const TRUSTS: SpellCatalogEntry[] = SPELLS.filter(s => s.type === 'Trust')
