// src/Vanalytics.Core/Services/GearSwapCodeGenerator.Generate.cs
using System.Text;
using Vanalytics.Core.DTOs.Blueprints;

namespace Vanalytics.Core.Services;

public static partial class GearSwapCodeGenerator
{
    public record GenerateResult(string Lua, List<string> Warnings);

    /// <summary>
    /// Generates a complete GearSwap .lua file from a blueprint graph and the resolved Gear Sets it
    /// references. Only sets actually wired to a trigger are emitted into get_sets(). Equip nodes
    /// referencing a set not present in <paramref name="sets"/> (e.g. deleted) are skipped and
    /// reported in Warnings. An empty graph still produces a valid (minimal) file.
    /// </summary>
    public static GenerateResult Generate(BlueprintGraphDto graph, IReadOnlyCollection<ResolvedGearSet> sets)
    {
        var warnings = new List<string>();
        var setsById = sets.GroupBy(s => s.Id).ToDictionary(g => g.Key, g => g.First());

        var reachable = ReachableEquips(graph);

        // Sets reached via a wired trigger branch (equip leaves).
        var flatSetIds = new List<long>();
        foreach (var target in reachable)
        {
            var setId = target.Data.GearSetId;
            if (setId is null) continue;
            if (!setsById.ContainsKey(setId.Value))
            {
                warnings.Add($"Gear set #{setId.Value} is referenced by the blueprint but no longer exists; that step was skipped.");
                continue;
            }
            if (!flatSetIds.Contains(setId.Value)) flatSetIds.Add(setId.Value);
        }

        // Overlay layers (equip leaves wired to a pin, and mode members) emit as top-level sets['Name']
        // so their set_combine(...) call can reference them by name.
        void AddOverlayIds(long? baseId, IReadOnlyList<long>? overlays)
        {
            if (overlays is not { Count: > 0 }) return;
            foreach (var o in overlays)
            {
                if (!setsById.ContainsKey(o))
                {
                    warnings.Add($"Gear set #{o} is referenced by the blueprint but no longer exists; that step was skipped.");
                    continue;
                }
                if (!flatSetIds.Contains(o)) flatSetIds.Add(o);
            }
            if (baseId is { } b && setsById.ContainsKey(b) && !flatSetIds.Contains(b)) flatSetIds.Add(b);
        }
        foreach (var leaf in reachable)
            AddOverlayIds(leaf.Data.GearSetId, leaf.Data.OverlaySetIds);
        foreach (var node in graph.Nodes.Where(n => n.Type == "mode"))
            foreach (var m in node.Data.Members ?? [])
                AddOverlayIds(m.GearSetId, m.OverlaySetIds);

        // Sets used as mode members — emitted even for cycle-only modes (no terminal pin wired).
        var modeMemberIds = new List<long>();
        foreach (var node in graph.Nodes.Where(n => n.Type == "mode"))
            foreach (var m in node.Data.Members ?? [])
            {
                if (m.OverlaySetIds is { Count: > 0 }) continue;    // layered member -> emitted via set_combine, not inline
                if (!setsById.ContainsKey(m.GearSetId))
                {
                    warnings.Add($"Gear set #{m.GearSetId} is referenced by the blueprint but no longer exists; that step was skipped.");
                    continue;
                }
                if (!modeMemberIds.Contains(m.GearSetId)) modeMemberIds.Add(m.GearSetId);
            }

        var allIds = flatSetIds.Concat(modeMemberIds).Distinct().ToList();
        var setNamesById = allIds.ToDictionary(id => id, id => setsById[id].Name);
        var modes = CollectModes(graph, setNamesById);

        var sb = new StringBuilder();
        sb.Append("-- Generated by Vanalytics. Edits will be overwritten on regenerate.\n\n");

        // File-top setup escape hatch (singleton): the first setup node with non-empty Code is emitted
        // verbatim before get_sets(). GearSwap runs top-level statements at file load, so includes,
        // helper functions, and on-load commands (e.g. a macro-book send_command) all belong here.
        var setup = graph.Nodes.FirstOrDefault(n => n.Type == "setup" && !string.IsNullOrWhiteSpace(n.Data.Code));
        if (setup is not null)
            sb.Append(setup.Data.Code!.Trim()).Append("\n\n");

        sb.Append("function get_sets()\n");
        sb.Append(EmitSets(flatSetIds.Select(id => setsById[id])));
        sb.Append(EmitModes(modes, setsById));
        sb.Append("end\n\n");
        sb.Append(EmitEvents(graph, setNamesById));
        sb.Append(EmitSelfCommand(modes));
        return new GenerateResult(sb.ToString().TrimEnd() + "\n", warnings);
    }

    private static string NodeType(BlueprintGraphDto graph, string nodeId) =>
        graph.Nodes.FirstOrDefault(n => n.Id == nodeId)?.Type ?? string.Empty;

    // Equip leaves reachable from any trigger via exec flow (through branch True/False), in
    // deterministic order: trigger edges in graph order, each branch expands true-subtree then
    // false-subtree. For a graph with no branches this equals the direct trigger->equip children
    // in edge order, so get_sets() emission order (and existing golden output) is preserved.
    // Sequential exec nodes (lua/print/chained equip) are walked via their 'out' edge.
    private static List<BlueprintNodeDto> ReachableEquips(BlueprintGraphDto graph)
    {
        var byId = graph.Nodes.ToDictionary(n => n.Id);
        var result = new List<BlueprintNodeDto>();
        var visited = new HashSet<string>();

        void Walk(string nodeId)
        {
            if (!visited.Add(nodeId)) return;
            if (!byId.TryGetValue(nodeId, out var node)) return;
            if (node.Type == "equip") result.Add(node);
            if (node.Type == "branch")
                foreach (var h in new[] { "true", "false" })
                    foreach (var e in graph.Edges.Where(e => e.Source == nodeId && e.SourceHandle == h))
                        Walk(e.Target);
            else
                // equip/mode/lua/print: follow the single exec 'out' chain so a set referenced only via
                // a chained equip still emits into get_sets(). No 'out' edge => terminal, as before.
                foreach (var e in graph.Edges.Where(e => e.Source == nodeId && e.SourceHandle == "out"))
                    Walk(e.Target);
        }

        foreach (var edge in graph.Edges)
        {
            if (!Triggers.ContainsKey(NodeType(graph, edge.Source))) continue;
            Walk(edge.Target);
        }
        return result;
    }
}
