// src/Vanalytics.Core/Services/GearSwapCodeGenerator.Generate.cs
using System.Text;
using Vanalytics.Core.DTOs.Workflows;

namespace Vanalytics.Core.Services;

public static partial class GearSwapCodeGenerator
{
    public record GenerateResult(string Lua, List<string> Warnings);

    /// <summary>
    /// Generates a complete GearSwap .lua file from a workflow graph and the resolved Gear Sets it
    /// references. Only sets actually wired to a trigger are emitted into get_sets(). Equip nodes
    /// referencing a set not present in <paramref name="sets"/> (e.g. deleted) are skipped and
    /// reported in Warnings. An empty graph still produces a valid (minimal) file.
    /// </summary>
    public static GenerateResult Generate(WorkflowGraphDto graph, IReadOnlyCollection<ResolvedGearSet> sets)
    {
        var warnings = new List<string>();
        var setsById = sets.GroupBy(s => s.Id).ToDictionary(g => g.Key, g => g.First());
        var equipById = graph.Nodes.Where(n => n.Type == "equip").ToDictionary(n => n.Id);

        // Sets reached via a wired trigger branch (equip leaves).
        var flatSetIds = new List<long>();
        foreach (var edge in graph.Edges)
        {
            if (!Triggers.ContainsKey(NodeType(graph, edge.Source))) continue;
            if (!equipById.TryGetValue(edge.Target, out var target)) continue;
            var setId = target.Data.GearSetId;
            if (setId is null) continue;
            if (!setsById.ContainsKey(setId.Value))
            {
                warnings.Add($"Gear set #{setId.Value} is referenced by the workflow but no longer exists; that step was skipped.");
                continue;
            }
            if (!flatSetIds.Contains(setId.Value)) flatSetIds.Add(setId.Value);
        }

        // Sets used as mode members — emitted even for cycle-only modes (no terminal pin wired).
        var modeMemberIds = new List<long>();
        foreach (var node in graph.Nodes.Where(n => n.Type == "mode"))
            foreach (var m in node.Data.Members ?? [])
            {
                if (!setsById.ContainsKey(m.GearSetId))
                {
                    warnings.Add($"Gear set #{m.GearSetId} is referenced by the workflow but no longer exists; that step was skipped.");
                    continue;
                }
                if (!modeMemberIds.Contains(m.GearSetId)) modeMemberIds.Add(m.GearSetId);
            }

        var allIds = flatSetIds.Concat(modeMemberIds).Distinct().ToList();
        var setNamesById = allIds.ToDictionary(id => id, id => setsById[id].Name);
        var modes = CollectModes(graph, setNamesById);

        var sb = new StringBuilder();
        sb.Append("-- Generated by Vanalytics. Edits will be overwritten on regenerate.\n\n");
        sb.Append("function get_sets()\n");
        sb.Append(EmitSets(flatSetIds.Select(id => setsById[id])));
        sb.Append(EmitModes(modes, setsById));
        sb.Append("end\n\n");
        sb.Append(EmitEvents(graph, setNamesById));
        sb.Append(EmitSelfCommand(modes));
        return new GenerateResult(sb.ToString().TrimEnd() + "\n", warnings);
    }

    private static string NodeType(WorkflowGraphDto graph, string nodeId) =>
        graph.Nodes.FirstOrDefault(n => n.Id == nodeId)?.Type ?? string.Empty;
}
